{{ if .Values.as_deployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment }}
  labels:
    app: {{ .Values.library }}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.library }}-app
  template:
    metadata:
      labels:
        app: {{ .Values.library }}-app
    spec:
      containers:
      - name: {{ .Values.library }}-app
        image: {{ .Values.test_app_image }}
        env:
          - name: SERVER_PORT
            value: "18080"
        readinessProbe:
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
          httpGet:
            host:
            scheme: HTTP
            path: /
            port: 18080
          initialDelaySeconds: 20
          periodSeconds: 5
        ports:
          - containerPort: 18080
            protocol: TCP
{{ end }}
