from utils import interfaces


class Test_PythonKafka:
    """ Test kafka compatibility with datadog python tracer """

    def setup_produce(self):
        """
            send request A to weblog : this request will produce a kafka message
            send request B to python buddy, this request will consume kafka message
        """

    def test_produce(self):
        """ Check that a message produced to kafka is correctly ingested by a Datadog python tracer"""
        # traces = interfaces.library.get_traces(request=A)
        # do whatever test we want on traces generated by request A

        # traces = interfaces.python_buddy.get_traces(request=B)
        # do whatever test we want on traces generated by request B

    def setup_consume(self):
        """
            send request A to python buddy : this request will produce a kafka message
            send request B to weblog, this request will consume kafka message
        """

    def test_consume(self):
        """ Check that a message by an app instrumented by a Datadog python tracer is correctly ingested """
        # traces = interfaces.library.get_traces(request=A)
        # do whatever test we want on traces generated by request A

        # traces = interfaces.python_buddy.get_traces(request=B)
        # do whatever test we want on traces generated by request B
