include:
  - local: "/utils/ci/gitlab/main.yml"
    inputs:
      stage: "build"
      libraries: "python"
      scenarios_groups: "all"
      excluded_scenarios: "DEBUGGER_EXPRESSION_LANGUAGE,APM_TRACING_E2E_SINGLE_SPAN,APM_TRACING_E2E_OTEL"
      ref: "$CI_COMMIT_SHA"
      push_to_test_optimization: true
  - local: "/utils/ci/gitlab/aws-ssi.yml"
    inputs:
      stage: "build"

stages:
  - build
  - system-tests-utils

build_ci_image:
  image: registry.ddbuild.io/images/docker:20.10.13-jammy
  interruptible: true
  tags:
    - docker-in-docker:amd64
  stage: build
  script:
    - IMAGE_TAG=$(cat utils/ci/gitlab/docker/system-tests.Dockerfile requirements.txt | sha256sum | cut -c1-12)
    - echo "CI_IMAGE=registry.ddbuild.io/system-tests/ci-runner:$IMAGE_TAG" >> build.env
    - >
      if docker manifest inspect registry.ddbuild.io/system-tests/ci-runner:$IMAGE_TAG > /dev/null 2>&1; then
        echo "Image already exists, skipping build";
      else
        docker build -f utils/ci/gitlab/docker/system-tests.Dockerfile -t registry.ddbuild.io/system-tests/ci-runner:$IMAGE_TAG . &&
        docker push registry.ddbuild.io/system-tests/ci-runner:$IMAGE_TAG;
      fi
  artifacts:
    reports:
      dotenv: build.env

check_merge_labels:
  image: registry.ddbuild.io/system-tests/base-image-builder
  tags:
    - arch:amd64
  id_tokens:
    DDOCTOSTS_ID_TOKEN:
      aud: dd-octo-sts
  needs: []
  stage: system-tests-utils
  before_script:
    - dd-octo-sts version
    - dd-octo-sts debug --scope DataDog/system-tests --policy self.gitlab-read
    - dd-octo-sts token --scope DataDog/system-tests --policy self.gitlab-read > token.txt
    - export DOCKER_LOGIN=$(aws ssm get-parameter --region us-east-1 --name ci.system-tests.docker-login-write --with-decryption --query "Parameter.Value" --out text)
    - export DOCKER_LOGIN_PASS=$(aws ssm get-parameter --region us-east-1 --name ci.system-tests.docker-login-pass-write --with-decryption --query "Parameter.Value" --out text)
  script:
    - export GITHUB_TOKEN=$(cat token.txt)
    - ./utils/scripts/get_pr_merged_labels.sh
  after_script:
    - dd-octo-sts revoke -t $(cat token.txt)
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"

generate_system_tests_lambda_proxy_image:
  image: registry.ddbuild.io/ci/libdatadog-build/ci_docker_base:100425777
  tags: ["docker-in-docker:amd64"]
  needs: []
  stage: system-tests-utils
  allow_failure: false
  before_script:
    - export DOCKER_LOGIN=$(aws ssm get-parameter --region us-east-1 --name ci.system-tests.docker-login-write --with-decryption --query "Parameter.Value" --out text)
    - export DOCKER_LOGIN_PASS=$(aws ssm get-parameter --region us-east-1 --name ci.system-tests.docker-login-pass-write --with-decryption --query "Parameter.Value" --out text)
    - echo "$DOCKER_LOGIN_PASS" | docker login --username "$DOCKER_LOGIN" --password-stdin
  script:
    - SYSTEM_TEST_BUILD_ATTEMPTS=3 SYSTEM_TEST_BUILD_TIMEOUT=240 ./build.sh -i lambda-proxy
    - docker push datadog/system-tests:lambda-proxy-v1
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"
      changes:
        - utils/build/docker/lambda_proxy/pyproject.toml
        - utils/build/docker/lambda-proxy.Dockerfile

generate_system_tests_lib_injection_images:
  extends: .base_job_k8s_docker_ssi
  needs: []
  stage: system-tests-utils
  allow_failure: true
  variables:
    PRIVATE_DOCKER_REGISTRY: 235494822917.dkr.ecr.us-east-1.amazonaws.com
    PRIVATE_DOCKER_REGISTRY_USER: AWS
  script:
    - aws ecr get-login-password | docker login --username ${PRIVATE_DOCKER_REGISTRY_USER} --password-stdin ${PRIVATE_DOCKER_REGISTRY}
    - ./lib-injection/build/build_lib_injection_images.sh $PRIVATE_DOCKER_REGISTRY
  rules:
    - if: '$SCHEDULED_JOB == "generate_system_tests_lib_injection_images"'
    - when: manual

