stages:
  - ruby_tracer
  - nodejs_tracer
  - java_tracer
  - python_tracer
  - dotnet_tracer
  - parse_results
  - before_tests
  - manual_images

.base_job_onboarding:
  only:
      - web
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/test-infra-definitions/runner:a58cc31c
  tags: ["arch:amd64"]
  before_script:
    # Setup AWS Credentials
    - mkdir -p ~/.aws
    - aws ssm get-parameter --region us-east-1 --name ci.system-tests.agent-qa-profile --with-decryption --query "Parameter.Value" --out text >> ~/.aws/config
    - export DD_API_KEY_ONBOARDING=$(aws ssm get-parameter --region us-east-1 --name ci.system-tests.dd-api-key-onboarding --with-decryption --query "Parameter.Value" --out text)
    - export DD_APP_KEY_ONBOARDING=$(aws ssm get-parameter --region us-east-1 --name ci.system-tests.dd-app-key-onboarding --with-decryption --query "Parameter.Value" --out text)
    - export ONBOARDING_AWS_INFRA_SUBNET_ID=$(aws ssm get-parameter --region us-east-1 --name ci.system-tests.aws-infra-subnet-id --with-decryption --query "Parameter.Value" --out text)
    - export ONBOARDING_AWS_INFRA_SECURITY_GROUPS_ID=$(aws ssm get-parameter --region us-east-1 --name ci.system-tests.aws-infra-securiy-groups-id --with-decryption --query "Parameter.Value" --out text)
    - export PULUMI_CONFIG_PASSPHRASE=$(aws ssm get-parameter --region us-east-1 --name ci.system-tests.pulumi-config-passphrase --with-decryption --query "Parameter.Value" --out text) 
    #Install plugins for PULUMI you need connect to gh. Sometimes this problem arises: GitHub rate limit exceeded
    - export GITHUB_TOKEN=$(aws ssm get-parameter --region us-east-1 --name ci.system-tests.gh-token --with-decryption --query "Parameter.Value" --out text) 
    #Avoid dockerhub rate limits
    - export DOCKER_LOGIN=$(aws ssm get-parameter --region us-east-1 --name ci.system-tests.docker-login --with-decryption --query "Parameter.Value" --out text) 
    - export DOCKER_LOGIN_PASS=$(aws ssm get-parameter --region us-east-1 --name ci.system-tests.docker-login-pass --with-decryption --query "Parameter.Value" --out text) 
    - export AWS_PROFILE=agent-qa-ci
    - pulumi login --local #"s3://dd-pulumi-state?region=us-east-1&awssdk=v2&profile=$AWS_PROFILE"
    - pulumi plugin install resource command 0.7.2
    - pulumi plugin install resource aws 5.41.0
  after_script:
    - SCENARIO_SUFIX=$(echo "$SCENARIO" | tr '[:upper:]' '[:lower:]')
    - REPORTS_PATH="reports/"
    - mkdir -p "$REPORTS_PATH"
    - cp -R logs_"${SCENARIO_SUFIX}" $REPORTS_PATH/
    - cp logs_"${SCENARIO_SUFIX}"/feature_parity.json "$REPORTS_PATH"/"${SCENARIO_SUFIX}".json
    - mv "$REPORTS_PATH"/logs_"${SCENARIO_SUFIX}" "$REPORTS_PATH"/logs_"${TEST_LIBRARY}"_"${ONBOARDING_FILTER_WEBLOG}"_"${SCENARIO_SUFIX}" 
  artifacts:
      when: always
      paths:
        - reports/
 
variables:
    # Do not modify this - must be the repository name for Kubernetes gitlab runners to run
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: system-tests #helm-charts
    TEST: 1
    DOCKER_REGISTRY: registry.ddbuild.io
    CI_DOCKER_IMAGE_BASE: $DOCKER_REGISTRY/ci/system-tests
    PROMOTION_TAG: current
    
onboarding_nodejs:
  extends: .base_job_onboarding
  stage: nodejs_tracer
  allow_failure: true
  dependencies: []
  only:
    - schedules
  variables:
    TEST_LIBRARY: "nodejs"
  parallel:
      matrix:
        - ONBOARDING_FILTER_ENV: [dev, prod]
          ONBOARDING_FILTER_WEBLOG: [test-app-nodejs]
          SCENARIO: [HOST_AUTO_INJECTION, HOST_AUTO_INJECTION_INSTALL_SCRIPT]
        - ONBOARDING_FILTER_ENV: [dev, prod]
          ONBOARDING_FILTER_WEBLOG: [test-shell-script]
          SCENARIO: [HOST_AUTO_INJECTION_BLOCK_LIST]    
        - ONBOARDING_FILTER_ENV: [dev, prod]
          ONBOARDING_FILTER_WEBLOG: [test-app-nodejs-container,test-app-nodejs-alpine]
          SCENARIO: [CONTAINER_AUTO_INJECTION, CONTAINER_AUTO_INJECTION_INSTALL_SCRIPT]
         
  script:
      - ./build.sh -i runner
      - timeout 2700s ./run.sh $SCENARIO --vm-weblog ${ONBOARDING_FILTER_WEBLOG} --vm-env ${ONBOARDING_FILTER_ENV} --vm-library ${TEST_LIBRARY} --vm-provider aws
      
onboarding_java:
  extends: .base_job_onboarding
  stage: java_tracer
  allow_failure: true
  dependencies: []
  only:
    - schedules
  variables:
    TEST_LIBRARY: "java"
  parallel:
      matrix:
        - ONBOARDING_FILTER_ENV: [dev, prod]
          ONBOARDING_FILTER_WEBLOG: [test-app-java]
          SCENARIO: [HOST_AUTO_INJECTION, HOST_AUTO_INJECTION_INSTALL_SCRIPT]
        - ONBOARDING_FILTER_ENV: [dev, prod]
          ONBOARDING_FILTER_WEBLOG: [test-shell-script]
          SCENARIO: [HOST_AUTO_INJECTION_BLOCK_LIST]      
        - ONBOARDING_FILTER_ENV: [dev, prod]
          ONBOARDING_FILTER_WEBLOG: [test-app-java-container,test-app-java-buildpack,test-app-java-alpine]
          SCENARIO: [CONTAINER_AUTO_INJECTION, CONTAINER_AUTO_INJECTION_INSTALL_SCRIPT]
  script:
      - ./build.sh -i runner
      - timeout 2700s ./run.sh $SCENARIO --vm-weblog ${ONBOARDING_FILTER_WEBLOG} --vm-env ${ONBOARDING_FILTER_ENV} --vm-library ${TEST_LIBRARY} --vm-provider aws

onboarding_python:
  extends: .base_job_onboarding
  stage: python_tracer
  allow_failure: true
  dependencies: []
  only:
    - schedules
  variables:
    TEST_LIBRARY: "python"
  parallel:
      matrix:
        - ONBOARDING_FILTER_ENV: [dev, prod]
          ONBOARDING_FILTER_WEBLOG: [test-app-python]
          SCENARIO: [HOST_AUTO_INJECTION, HOST_AUTO_INJECTION_INSTALL_SCRIPT]
        - ONBOARDING_FILTER_ENV: [dev, prod]
          ONBOARDING_FILTER_WEBLOG: [test-shell-script]
          SCENARIO: [HOST_AUTO_INJECTION_BLOCK_LIST]    
        - ONBOARDING_FILTER_ENV: [dev, prod]
          ONBOARDING_FILTER_WEBLOG: [test-app-python-container,test-app-python-alpine]
          SCENARIO: [CONTAINER_AUTO_INJECTION, CONTAINER_AUTO_INJECTION_INSTALL_SCRIPT]
  script:
      - ./build.sh -i runner
      - timeout 2700s ./run.sh $SCENARIO --vm-weblog ${ONBOARDING_FILTER_WEBLOG} --vm-env ${ONBOARDING_FILTER_ENV} --vm-library ${TEST_LIBRARY} --vm-provider aws

onboarding_dotnet:
  extends: .base_job_onboarding
  stage: dotnet_tracer
  allow_failure: true
  dependencies: []
  only:
    - schedules
  variables:
    TEST_LIBRARY: "dotnet"
  parallel:
      matrix:
        - ONBOARDING_FILTER_ENV: [dev, prod]
          ONBOARDING_FILTER_WEBLOG: [test-app-dotnet]
          SCENARIO: [HOST_AUTO_INJECTION, HOST_AUTO_INJECTION_INSTALL_SCRIPT]
        - ONBOARDING_FILTER_ENV: [dev, prod]
          ONBOARDING_FILTER_WEBLOG: [test-shell-script]
          SCENARIO: [HOST_AUTO_INJECTION_BLOCK_LIST]    
        - ONBOARDING_FILTER_ENV: [dev, prod]
          ONBOARDING_FILTER_WEBLOG: [test-app-dotnet-container]
          SCENARIO: [CONTAINER_AUTO_INJECTION, CONTAINER_AUTO_INJECTION_INSTALL_SCRIPT]
  script:
      - ./build.sh -i runner
      - timeout 2700s ./run.sh $SCENARIO --vm-weblog ${ONBOARDING_FILTER_WEBLOG} --vm-env ${ONBOARDING_FILTER_ENV} --vm-library ${TEST_LIBRARY} --vm-provider aws

onboarding_ruby:
  extends: .base_job_onboarding
  stage: ruby_tracer
  allow_failure: true
  dependencies: []
  only:
    - schedules
  variables:
    TEST_LIBRARY: "ruby"
  parallel:
      matrix:
        - ONBOARDING_FILTER_ENV: [dev, prod]
          ONBOARDING_FILTER_WEBLOG: [test-app-ruby]
          SCENARIO: [HOST_AUTO_INJECTION, HOST_AUTO_INJECTION_INSTALL_SCRIPT]
        - ONBOARDING_FILTER_ENV: [dev, prod]
          ONBOARDING_FILTER_WEBLOG: [test-shell-script]
          SCENARIO: [HOST_AUTO_INJECTION_BLOCK_LIST]      
        - ONBOARDING_FILTER_ENV: [dev, prod]
          ONBOARDING_FILTER_WEBLOG: [test-app-ruby-container]
          SCENARIO: [CONTAINER_AUTO_INJECTION, CONTAINER_AUTO_INJECTION_INSTALL_SCRIPT]
  script:
      - ./build.sh -i runner
      - timeout 2700s ./run.sh $SCENARIO --vm-weblog ${ONBOARDING_FILTER_WEBLOG} --vm-env ${ONBOARDING_FILTER_ENV} --vm-library ${TEST_LIBRARY} --vm-provider aws

onboarding_parse_results:
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/test-infra-definitions/runner:a58cc31c
  tags: ["arch:amd64"]
  stage: parse_results
  only:
    - schedules
  before_script:
    #We need authenticate on git repository
    - export FP_IMPORT_URL=$(aws ssm get-parameter --region us-east-1 --name ci.system-tests.fp-import-url --with-decryption --query "Parameter.Value" --out text) 
    - export FP_API_KEY=$(aws ssm get-parameter --region us-east-1 --name ci.system-tests.fp-api-key --with-decryption --query "Parameter.Value" --out text) 
  script:
      - |
        for folder in reports/logs*/ ; do
          if [ -e ./${folder}feature_parity.json ]
          then
            curl -X POST ${FP_IMPORT_URL} \
              --fail \
              --header "Content-Type: application/json" \
              --header "FP_API_KEY: ${FP_API_KEY}" \
              --data "@./${folder}feature_parity.json" \
              --include
          fi
        done

check_merge_labels:
  image: registry.ddbuild.io/images/ci_docker_base
  tags: ["runner:docker"]
  stage: before_tests
  before_script:
    - export GH_TOKEN=$(aws ssm get-parameter --region us-east-1 --name ci.system-tests.gh-token --with-decryption --query "Parameter.Value" --out text) 
    - export DOCKER_LOGIN=$(aws ssm get-parameter --region us-east-1 --name ci.system-tests.docker-login-write --with-decryption --query "Parameter.Value" --out text) 
    - export DOCKER_LOGIN_PASS=$(aws ssm get-parameter --region us-east-1 --name ci.system-tests.docker-login-pass-write --with-decryption --query "Parameter.Value" --out text) 
  script:
    - ./utils/scripts/get_pr_merged_labels.sh
  #rules:
  #  - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"

build-image:
  stage: manual-images
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push"
      changes:
        - gitlab/Dockerfile.*
    - when: manual
      allow_failure: true
  tags: [ "arch:amd64" ]
  image: $DOCKER_REGISTRY/docker:20.10.13
  script:
    - >
      docker buildx build 
      --tag $CI_DOCKER_IMAGE_BASE/gitlab:current
      --platform linux/amd64
      --push
      --file gitlab/Dockerfile.gitlab
      .