include:
  - local: "/utils/ci/gitlab/main.yml"
    inputs:
      stage: "test"
      libraries: "python"
      scenarios_groups: "all"
      excluded_scenarios: "DEBUGGER_EXPRESSION_LANGUAGE"
      ref: "$CI_COMMIT_SHA"

stages:
  - build
  - test
  - run

build_ci_image:
  image: registry.ddbuild.io/images/docker:20.10.13-jammy
  interruptible: true
  tags:
    - docker-in-docker:amd64
  stage: build
  script:
    - IMAGE_TAG=$(cat utils/ci/gitlab/docker/system-tests.Dockerfile requirements.txt | sha256sum | cut -c1-12)
    - echo "CI_IMAGE=registry.ddbuild.io/system-tests/ci-runner:$IMAGE_TAG" >> build.env
    - >
      if docker manifest inspect registry.ddbuild.io/system-tests/ci-runner:$IMAGE_TAG > /dev/null 2>&1; then
        echo "Image already exists, skipping build";
      else
        docker build -f utils/ci/gitlab/docker/system-tests.Dockerfile -t registry.ddbuild.io/system-tests/ci-runner:$IMAGE_TAG . &&
        docker push registry.ddbuild.io/system-tests/ci-runner:$IMAGE_TAG;
      fi
  artifacts:
    reports:
      dotenv: build.env
