image: tiangolo/docker-with-compose

.base_job:
  # image: $CI_IMAGE
  needs: []
  before_script:
    - apk add bash jq git unzip curl
    - pip install pyyaml awscli
    - aws --version && docker --version && docker-compose --version
    - export DD_API_KEY=$(aws ssm get-parameter --region us-east-1 --name ci.system-tests.dd_api_key --with-decryption --query "Parameter.Value" --out text)
    - export GL_TOKEN=$(aws ssm get-parameter --region us-east-1 --name ci.system-tests.gl_token --with-decryption --query "Parameter.Value" --out text)
    - export CIRCLECI_TOKEN=$(aws ssm get-parameter --region us-east-1 --name ci.system-tests.circleci_token --with-decryption --query "Parameter.Value" --out text)

cross-components:
  extends: .base_job
  stage: test
  tags: ["runner:docker"]
  parallel:
    matrix:
      - TEST_LIBRARY: php
        WEBLOG_VARIANT: apache-mod-8.0
  script:
    - ./utils/scripts/load-binary.sh $TEST_LIBRARY
    - ./build.sh
    - ./run.sh
    - ./run.sh SAMPLING
  artifacts:
    when: always
    paths:
      - binaries/
      - logs/
      - logs_sampling_rate/

cross-component-agent:
  extends: .base_job
  stage: test
  tags: ["runner:docker"]
  parallel:
    matrix:
      - TEST_LIBRARY: php
        WEBLOG_VARIANT: apache-mod-8.0
  script:
    - ./utils/scripts/load-binary.sh agent
    - ./utils/scripts/load-binary.sh $TEST_LIBRARY
    - ./build.sh
    - ./run.sh
    - ./run.sh SAMPLING
  artifacts:
    when: always
    paths:
      - binaries/
      - logs/
      - logs_sampling_rate/


onboarding_scenarios:
  stage: test
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/test-infra-definitions/runner:a58cc31c
  tags: ["arch:amd64"]
  only:
    - schedules
  before_script:
    # Setup AWS Credentials
    - mkdir -p ~/.aws
    - set +x
    - aws ssm get-parameter --region us-east-1 --name ci.system-tests.agent-qa-profile --with-decryption --query "Parameter.Value" --out text >> ~/.aws/config
    - set -x
    - export AWS_PROFILE=agent-qa-ci
    - pulumi login .
  parallel:
    matrix:
      - TEST_LIBRARY: nodejs
  script:
    - build.sh -i runner
    - run.sh ONBOARDING_HOST
  artifacts:
    when: always
    paths:
      - logs/
      - logs_onboarding_host/