// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: protos/apm_test_otel_client.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartOtelSpanArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *StartOtelSpanArgs) Reset() {
	*x = StartOtelSpanArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_apm_test_otel_client_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartOtelSpanArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOtelSpanArgs) ProtoMessage() {}

func (x *StartOtelSpanArgs) ProtoReflect() protoreflect.Message {
	mi := &file_protos_apm_test_otel_client_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOtelSpanArgs.ProtoReflect.Descriptor instead.
func (*StartOtelSpanArgs) Descriptor() ([]byte, []int) {
	return file_protos_apm_test_otel_client_proto_rawDescGZIP(), []int{0}
}

func (x *StartOtelSpanArgs) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StartOtelSpanReturn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpanId  []byte `protobuf:"bytes,1,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	TraceId []byte `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
}

func (x *StartOtelSpanReturn) Reset() {
	*x = StartOtelSpanReturn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_apm_test_otel_client_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartOtelSpanReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOtelSpanReturn) ProtoMessage() {}

func (x *StartOtelSpanReturn) ProtoReflect() protoreflect.Message {
	mi := &file_protos_apm_test_otel_client_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOtelSpanReturn.ProtoReflect.Descriptor instead.
func (*StartOtelSpanReturn) Descriptor() ([]byte, []int) {
	return file_protos_apm_test_otel_client_proto_rawDescGZIP(), []int{1}
}

func (x *StartOtelSpanReturn) GetSpanId() []byte {
	if x != nil {
		return x.SpanId
	}
	return nil
}

func (x *StartOtelSpanReturn) GetTraceId() []byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

//	message InjectHeadersArgs {
//	 uint64 span_id = 1;
//	}
//
//	message InjectHeadersReturn {
//	   optional DistributedHTTPHeaders http_headers = 1;
//	}
type FinishOtelSpanArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FinishOtelSpanArgs) Reset() {
	*x = FinishOtelSpanArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_apm_test_otel_client_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishOtelSpanArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishOtelSpanArgs) ProtoMessage() {}

func (x *FinishOtelSpanArgs) ProtoReflect() protoreflect.Message {
	mi := &file_protos_apm_test_otel_client_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishOtelSpanArgs.ProtoReflect.Descriptor instead.
func (*FinishOtelSpanArgs) Descriptor() ([]byte, []int) {
	return file_protos_apm_test_otel_client_proto_rawDescGZIP(), []int{2}
}

func (x *FinishOtelSpanArgs) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type FinishOtelSpanReturn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FinishOtelSpanReturn) Reset() {
	*x = FinishOtelSpanReturn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_apm_test_otel_client_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishOtelSpanReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishOtelSpanReturn) ProtoMessage() {}

func (x *FinishOtelSpanReturn) ProtoReflect() protoreflect.Message {
	mi := &file_protos_apm_test_otel_client_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishOtelSpanReturn.ProtoReflect.Descriptor instead.
func (*FinishOtelSpanReturn) Descriptor() ([]byte, []int) {
	return file_protos_apm_test_otel_client_proto_rawDescGZIP(), []int{3}
}

//	message SpanSetMetaArgs {
//	 uint64 span_id = 1;
//	 string key = 2;
//	 string value = 3;
//	}
//
// message SpanSetMetaReturn {}
//
//	message SpanSetMetricArgs {
//	 uint64 span_id = 1;
//	 string key = 2;
//	 float value = 3;
//	}
//
// message SpanSetMetricReturn {}
//
//	message SpanSetErrorArgs {
//	 uint64 span_id = 1;
//	 optional string type = 2;
//	 optional string message = 3;
//	 optional string stack = 4;
//	}
//
// message SpanSetErrorReturn {}
type FlushOtelSpansArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FlushOtelSpansArgs) Reset() {
	*x = FlushOtelSpansArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_apm_test_otel_client_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlushOtelSpansArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushOtelSpansArgs) ProtoMessage() {}

func (x *FlushOtelSpansArgs) ProtoReflect() protoreflect.Message {
	mi := &file_protos_apm_test_otel_client_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushOtelSpansArgs.ProtoReflect.Descriptor instead.
func (*FlushOtelSpansArgs) Descriptor() ([]byte, []int) {
	return file_protos_apm_test_otel_client_proto_rawDescGZIP(), []int{4}
}

type FlushOtelSpansReturn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FlushOtelSpansReturn) Reset() {
	*x = FlushOtelSpansReturn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_apm_test_otel_client_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlushOtelSpansReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushOtelSpansReturn) ProtoMessage() {}

func (x *FlushOtelSpansReturn) ProtoReflect() protoreflect.Message {
	mi := &file_protos_apm_test_otel_client_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushOtelSpansReturn.ProtoReflect.Descriptor instead.
func (*FlushOtelSpansReturn) Descriptor() ([]byte, []int) {
	return file_protos_apm_test_otel_client_proto_rawDescGZIP(), []int{5}
}

type FlushOtelTraceStatsArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FlushOtelTraceStatsArgs) Reset() {
	*x = FlushOtelTraceStatsArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_apm_test_otel_client_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlushOtelTraceStatsArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushOtelTraceStatsArgs) ProtoMessage() {}

func (x *FlushOtelTraceStatsArgs) ProtoReflect() protoreflect.Message {
	mi := &file_protos_apm_test_otel_client_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushOtelTraceStatsArgs.ProtoReflect.Descriptor instead.
func (*FlushOtelTraceStatsArgs) Descriptor() ([]byte, []int) {
	return file_protos_apm_test_otel_client_proto_rawDescGZIP(), []int{6}
}

type FlushOtelTraceStatsReturn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FlushOtelTraceStatsReturn) Reset() {
	*x = FlushOtelTraceStatsReturn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_apm_test_otel_client_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlushOtelTraceStatsReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushOtelTraceStatsReturn) ProtoMessage() {}

func (x *FlushOtelTraceStatsReturn) ProtoReflect() protoreflect.Message {
	mi := &file_protos_apm_test_otel_client_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushOtelTraceStatsReturn.ProtoReflect.Descriptor instead.
func (*FlushOtelTraceStatsReturn) Descriptor() ([]byte, []int) {
	return file_protos_apm_test_otel_client_proto_rawDescGZIP(), []int{7}
}

type StopOtelTracerArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopOtelTracerArgs) Reset() {
	*x = StopOtelTracerArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_apm_test_otel_client_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopOtelTracerArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopOtelTracerArgs) ProtoMessage() {}

func (x *StopOtelTracerArgs) ProtoReflect() protoreflect.Message {
	mi := &file_protos_apm_test_otel_client_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopOtelTracerArgs.ProtoReflect.Descriptor instead.
func (*StopOtelTracerArgs) Descriptor() ([]byte, []int) {
	return file_protos_apm_test_otel_client_proto_rawDescGZIP(), []int{8}
}

type StopOtelTracerReturn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopOtelTracerReturn) Reset() {
	*x = StopOtelTracerReturn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_apm_test_otel_client_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopOtelTracerReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopOtelTracerReturn) ProtoMessage() {}

func (x *StopOtelTracerReturn) ProtoReflect() protoreflect.Message {
	mi := &file_protos_apm_test_otel_client_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopOtelTracerReturn.ProtoReflect.Descriptor instead.
func (*StopOtelTracerReturn) Descriptor() ([]byte, []int) {
	return file_protos_apm_test_otel_client_proto_rawDescGZIP(), []int{9}
}

var File_protos_apm_test_otel_client_proto protoreflect.FileDescriptor

var file_protos_apm_test_otel_client_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x70, 0x6d, 0x5f, 0x74, 0x65, 0x73,
	0x74, 0x5f, 0x6f, 0x74, 0x65, 0x6c, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x27, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4f, 0x74, 0x65, 0x6c,
	0x53, 0x70, 0x61, 0x6e, 0x41, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x49, 0x0a, 0x13,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x4f, 0x74, 0x65, 0x6c, 0x53, 0x70, 0x61, 0x6e, 0x52, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x70, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x73, 0x70, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x22, 0x24, 0x0a, 0x12, 0x46, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x4f, 0x74, 0x65, 0x6c, 0x53, 0x70, 0x61, 0x6e, 0x41, 0x72, 0x67, 0x73, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x22, 0x16, 0x0a,
	0x14, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4f, 0x74, 0x65, 0x6c, 0x53, 0x70, 0x61, 0x6e, 0x52,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x22, 0x14, 0x0a, 0x12, 0x46, 0x6c, 0x75, 0x73, 0x68, 0x4f, 0x74,
	0x65, 0x6c, 0x53, 0x70, 0x61, 0x6e, 0x73, 0x41, 0x72, 0x67, 0x73, 0x22, 0x16, 0x0a, 0x14, 0x46,
	0x6c, 0x75, 0x73, 0x68, 0x4f, 0x74, 0x65, 0x6c, 0x53, 0x70, 0x61, 0x6e, 0x73, 0x52, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x22, 0x19, 0x0a, 0x17, 0x46, 0x6c, 0x75, 0x73, 0x68, 0x4f, 0x74, 0x65, 0x6c,
	0x54, 0x72, 0x61, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x41, 0x72, 0x67, 0x73, 0x22, 0x1b,
	0x0a, 0x19, 0x46, 0x6c, 0x75, 0x73, 0x68, 0x4f, 0x74, 0x65, 0x6c, 0x54, 0x72, 0x61, 0x63, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x22, 0x14, 0x0a, 0x12, 0x53,
	0x74, 0x6f, 0x70, 0x4f, 0x74, 0x65, 0x6c, 0x54, 0x72, 0x61, 0x63, 0x65, 0x72, 0x41, 0x72, 0x67,
	0x73, 0x22, 0x16, 0x0a, 0x14, 0x53, 0x74, 0x6f, 0x70, 0x4f, 0x74, 0x65, 0x6c, 0x54, 0x72, 0x61,
	0x63, 0x65, 0x72, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x32, 0xcf, 0x02, 0x0a, 0x0d, 0x41, 0x50,
	0x4d, 0x4f, 0x74, 0x65, 0x6c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x3b, 0x0a, 0x0d, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x4f, 0x74, 0x65, 0x6c, 0x53, 0x70, 0x61, 0x6e, 0x12, 0x12, 0x2e, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x4f, 0x74, 0x65, 0x6c, 0x53, 0x70, 0x61, 0x6e, 0x41, 0x72, 0x67, 0x73,
	0x1a, 0x14, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4f, 0x74, 0x65, 0x6c, 0x53, 0x70, 0x61, 0x6e,
	0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x69,
	0x73, 0x68, 0x4f, 0x74, 0x65, 0x6c, 0x53, 0x70, 0x61, 0x6e, 0x12, 0x13, 0x2e, 0x46, 0x69, 0x6e,
	0x69, 0x73, 0x68, 0x4f, 0x74, 0x65, 0x6c, 0x53, 0x70, 0x61, 0x6e, 0x41, 0x72, 0x67, 0x73, 0x1a,
	0x15, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4f, 0x74, 0x65, 0x6c, 0x53, 0x70, 0x61, 0x6e,
	0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0a, 0x46, 0x6c, 0x75, 0x73,
	0x68, 0x53, 0x70, 0x61, 0x6e, 0x73, 0x12, 0x13, 0x2e, 0x46, 0x6c, 0x75, 0x73, 0x68, 0x4f, 0x74,
	0x65, 0x6c, 0x53, 0x70, 0x61, 0x6e, 0x73, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x15, 0x2e, 0x46, 0x6c,
	0x75, 0x73, 0x68, 0x4f, 0x74, 0x65, 0x6c, 0x53, 0x70, 0x61, 0x6e, 0x73, 0x52, 0x65, 0x74, 0x75,
	0x72, 0x6e, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0f, 0x46, 0x6c, 0x75, 0x73, 0x68, 0x54, 0x72, 0x61,
	0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x18, 0x2e, 0x46, 0x6c, 0x75, 0x73, 0x68, 0x4f,
	0x74, 0x65, 0x6c, 0x54, 0x72, 0x61, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x41, 0x72, 0x67,
	0x73, 0x1a, 0x1a, 0x2e, 0x46, 0x6c, 0x75, 0x73, 0x68, 0x4f, 0x74, 0x65, 0x6c, 0x54, 0x72, 0x61,
	0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x22, 0x00, 0x12,
	0x3a, 0x0a, 0x0a, 0x53, 0x74, 0x6f, 0x70, 0x54, 0x72, 0x61, 0x63, 0x65, 0x72, 0x12, 0x13, 0x2e,
	0x53, 0x74, 0x6f, 0x70, 0x4f, 0x74, 0x65, 0x6c, 0x54, 0x72, 0x61, 0x63, 0x65, 0x72, 0x41, 0x72,
	0x67, 0x73, 0x1a, 0x15, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x4f, 0x74, 0x65, 0x6c, 0x54, 0x72, 0x61,
	0x63, 0x65, 0x72, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protos_apm_test_otel_client_proto_rawDescOnce sync.Once
	file_protos_apm_test_otel_client_proto_rawDescData = file_protos_apm_test_otel_client_proto_rawDesc
)

func file_protos_apm_test_otel_client_proto_rawDescGZIP() []byte {
	file_protos_apm_test_otel_client_proto_rawDescOnce.Do(func() {
		file_protos_apm_test_otel_client_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_apm_test_otel_client_proto_rawDescData)
	})
	return file_protos_apm_test_otel_client_proto_rawDescData
}

var file_protos_apm_test_otel_client_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_protos_apm_test_otel_client_proto_goTypes = []interface{}{
	(*StartOtelSpanArgs)(nil),         // 0: StartOtelSpanArgs
	(*StartOtelSpanReturn)(nil),       // 1: StartOtelSpanReturn
	(*FinishOtelSpanArgs)(nil),        // 2: FinishOtelSpanArgs
	(*FinishOtelSpanReturn)(nil),      // 3: FinishOtelSpanReturn
	(*FlushOtelSpansArgs)(nil),        // 4: FlushOtelSpansArgs
	(*FlushOtelSpansReturn)(nil),      // 5: FlushOtelSpansReturn
	(*FlushOtelTraceStatsArgs)(nil),   // 6: FlushOtelTraceStatsArgs
	(*FlushOtelTraceStatsReturn)(nil), // 7: FlushOtelTraceStatsReturn
	(*StopOtelTracerArgs)(nil),        // 8: StopOtelTracerArgs
	(*StopOtelTracerReturn)(nil),      // 9: StopOtelTracerReturn
}
var file_protos_apm_test_otel_client_proto_depIdxs = []int32{
	0, // 0: APMOtelClient.StartOtelSpan:input_type -> StartOtelSpanArgs
	2, // 1: APMOtelClient.FinishOtelSpan:input_type -> FinishOtelSpanArgs
	4, // 2: APMOtelClient.FlushSpans:input_type -> FlushOtelSpansArgs
	6, // 3: APMOtelClient.FlushTraceStats:input_type -> FlushOtelTraceStatsArgs
	8, // 4: APMOtelClient.StopTracer:input_type -> StopOtelTracerArgs
	1, // 5: APMOtelClient.StartOtelSpan:output_type -> StartOtelSpanReturn
	3, // 6: APMOtelClient.FinishOtelSpan:output_type -> FinishOtelSpanReturn
	5, // 7: APMOtelClient.FlushSpans:output_type -> FlushOtelSpansReturn
	7, // 8: APMOtelClient.FlushTraceStats:output_type -> FlushOtelTraceStatsReturn
	9, // 9: APMOtelClient.StopTracer:output_type -> StopOtelTracerReturn
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_apm_test_otel_client_proto_init() }
func file_protos_apm_test_otel_client_proto_init() {
	if File_protos_apm_test_otel_client_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_apm_test_otel_client_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartOtelSpanArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_apm_test_otel_client_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartOtelSpanReturn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_apm_test_otel_client_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishOtelSpanArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_apm_test_otel_client_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishOtelSpanReturn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_apm_test_otel_client_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlushOtelSpansArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_apm_test_otel_client_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlushOtelSpansReturn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_apm_test_otel_client_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlushOtelTraceStatsArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_apm_test_otel_client_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlushOtelTraceStatsReturn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_apm_test_otel_client_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopOtelTracerArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_apm_test_otel_client_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopOtelTracerReturn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_apm_test_otel_client_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_apm_test_otel_client_proto_goTypes,
		DependencyIndexes: file_protos_apm_test_otel_client_proto_depIdxs,
		MessageInfos:      file_protos_apm_test_otel_client_proto_msgTypes,
	}.Build()
	File_protos_apm_test_otel_client_proto = out.File
	file_protos_apm_test_otel_client_proto_rawDesc = nil
	file_protos_apm_test_otel_client_proto_goTypes = nil
	file_protos_apm_test_otel_client_proto_depIdxs = nil
}
