name: Get_target_branch
description: "Gets target branch from the PR description"
inputs:
  text:
    description: "Text from which to extract the target branch"
    required: true
outputs:
  target-branch:
    description: "Target branch"
    value: ${{ steps.extract.outputs.target-branch }}

runs:
  using: composite
  steps:
    - name: Extract target branch
      id: extract
      shell: bash
      run: |
        LIBS=$(python -m utils.const LIBRARIES all)
        branch=$(echo "${INPUTS_TEXT}" | grep -ioP "\[(?:${LIBS}|agent)@[^]]+(?=\])" | tr -d '[:space:]' || true)

        echo "target-branch=${branch#*@}" >> $GITHUB_OUTPUT

      # the preferred approach to handling untrusted input is to set the value of the expression to an intermediate environment variable
      env:
        INPUTS_TEXT: ${{ inputs.text }}
