name: Get_target_branch
description: "Gets target branch from the PR description"
inputs:
  text:
    description: "Text from which to extract the target branch"
    required: true
outputs:
  target-branch:
    description: "Target branch"
    value: ${{ steps.extract.outputs.target-branch }}

runs:
  using: composite
  steps:
    - name: Extract target branch
      id: extract
      if: ${{ contains(inputs.text, '[branch:') }}
      shell: bash
      run: |
        echo "target-branch=$(echo "${{ inputs.text }}" | grep -oP '(?<=[branch:).*' | tr -d ' ' | tr -d ']')" >> $GITHUB_OUTPUT
