# Unless explicitly stated otherwise all files in this repository are licensed under the the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2021 Datadog, Inc.

version: "2.4"
services:

  weblog:
    image: system_tests/weblog
    healthcheck:
      test: ["CMD", "curl", "-f", "http://weblog:7777"]
      interval: 1s
      start_period: 3s
      retries: 25
    environment:
      - DD_AGENT_HOST=agent
      - DD_TRACE_AGENT_PORT=8126
      - DD_APPSEC_ENABLED=${DD_APPSEC_ENABLED:-}
    volumes:
      - ./${SYSTEMTESTS_LOG_FOLDER:-logs}/docker/weblog/logs/:/var/log/system-tests
    ports:
      - "7777:7777"
    depends_on:
      agent:
        condition: service_healthy

  agent:
    image: system_tests/agent
    environment:
      - DD_API_KEY
      - DD_ENV=system-tests
      - DD_SITE=${DD_SITE:-datad0g.com}

  runner:
    image: system_tests/runner
    environment:
      - COLUMNS=${COLUMNS:-120}
      - PYTHONPATH=/app
      - DD_SITE=${DD_SITE:-datad0g.com}
      - DD_APPSEC_ENABLED=${DD_APPSEC_ENABLED:-}
      - SYSTEM_TESTS_LIBRARY=${SYSTEM_TESTS_LIBRARY}
    volumes:
      - ./pytest.ini:/app/pytest.ini
      - ./conftest.py:/app/conftest.py
      - ./tests/:/app/tests/
      - ./utils/:/app/utils/
      - ./${SYSTEMTESTS_LOG_FOLDER:-logs}/:/app/logs/
      - ./scenarios/:/app/scenarios/
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      weblog:
        condition: service_healthy
    command: python scenarios/perfs/main.py
