targetSystem: "linux"
agents:
  enabled: false
datadog:
  clusterName: $$CLUSTER_NAME$$
  tags: []
  # datadog.kubelet.tlsVerify should be `false` on kind and minikube
  # to establish communication with the kubelet
  kubelet:
    tlsVerify: "false"
clusterAgent:
  enabled: true

  livenessProbe:
    initialDelaySeconds: 15
    periodSeconds: 15
    timeoutSeconds: 10
    successThreshold: 1
    failureThreshold: 12

  readinessProbe:
    initialDelaySeconds: 15
    periodSeconds: 15
    timeoutSeconds: 10
    successThreshold: 1
    failureThreshold: 12

  image:
   #comment name, tag and repository to test cluster-agent for local Mac M1
   # name: ""
   # tag: master
   # repository: datadog/cluster-agent-dev
    pullPolicy: Never
    doNotCheckTag: true
  admissionController:
    configMode: socket
