version: 2.1

jobs:
  system-tests:
    machine:
      # https://support.circleci.com/hc/en-us/articles/360007324514-How-can-I-use-Docker-volume-mounting-on-CircleCI-
      image: ubuntu-2004:current
    resource_class: large
    steps:
      - checkout

      - run:
          name: versions
          command: |
            docker --version
            python --version

      - run:
          name: Build
          command: ./build.sh java

      - run:
          name: Run
          command: ./run.sh

      - store_artifacts:
          path: logs
          destination: system-tests.tar.gz

workflows:
  test:
    jobs:
      - system-tests
