reason_regex = r" ?(?:\((.*)\))?"
skip_declaration_regex = rf"(bug|flaky|incomplete_test_app|irrelevant|missing_feature){reason_regex}"
version_regex = r"(?:\d+\.\d+\.\d+|\d+\.\d+|\d+)[.+-]?[.\w+-]*"
simple_regex = rf"(>|>=|v)?({version_regex}){reason_regex}"
full_regex = rf"(v)?([^()]*){reason_regex}"
default_manifests_path = "manifests/"
