import pytest

from utils._context.constants import WeblogCategory

from .core import scenario_groups
from .endtoend import EndToEndScenario


class ThreadContextSharingScenario(EndToEndScenario):
    """Exercises CWS (Cloud Workload Security) thread-context sharing: a tracer that
    implements it publishes the trace_id/span_id of the span active on a thread, so
    that system-probe's runtime security module can stamp them (as dd.trace_id /
    dd.span_id) onto the SECL security event generated by a syscall happening on that
    same thread.

    The weblog contract is documented in docs/understand/weblogs/end-to-end_weblog.md
    under "GET /security/thread_context_sharing". No tracer implements it yet - test
    classes using this scenario should be marked `@missing_feature` per-library until
    each tracer's implementation lands.

    CWS security events are observed through the agent's proxy-captured HTTPS traffic
    (`/api/v2/logs`), decoded via `tests/cws/utils.py` - the same way this scenario
    already observes telemetry, remote config, etc.
    """

    def __init__(self, name: str, doc: str) -> None:
        super().__init__(
            name=name,
            doc=doc,
            weblog_categories=[WeblogCategory.dd_trace],
            appsec_enabled=False,  # unrelated to this feature, keep the CWS signal clean
            scenario_groups=[scenario_groups.thread_context_sharing],
            weblog_env={
                "DD_TRACE_OTEL_CTX_ENABLED": "true",
            },
        )

    def configure(self, config: pytest.Config):
        super().configure(config)

        if self.weblog_infra.library_name == "java":
            self.weblog_container.environment["DD_PROFILING_ENABLED"] = "true"

        agent = self.agent_container

        agent.environment["DD_RUNTIME_SECURITY_CONFIG_ENABLED"] = "true"

        # span_tracking makes system-probe read the tracer's thread context; the self test is
        # the readiness signal the tests wait on (see tests/cws/utils.py).
        agent.environment["DD_RUNTIME_SECURITY_CONFIG_SPAN_TRACKING_ENABLED"] = "true"
        agent.environment["DD_RUNTIME_SECURITY_CONFIG_SELF_TEST_ENABLED"] = "true"

        agent.volumes["./utils/build/docker/agent/runtime-security.d"] = {
            "bind": "/etc/datadog-agent/runtime-security.d",
            "mode": "ro",
        }

        # Required for CWS to see host processes and load eBPF programs. Mirrors
        # datadog-agent's documented Docker setup for Cloud Workload Security:
        # https://docs.datadoghq.com/security/workload_protection/setup/agent/docker/
        agent.pid_mode = "host"
        agent.cap_add = [
            "SYS_ADMIN",
            "SYS_RESOURCE",
            "SYS_PTRACE",
            "NET_ADMIN",
            "NET_BROADCAST",
            "IPC_LOCK",
            "CHOWN",
        ]
        agent.security_opt = ["apparmor:unconfined"]
        agent.volumes["/etc/passwd"] = {"bind": "/etc/passwd", "mode": "ro"}
        agent.volumes["/etc/group"] = {"bind": "/etc/group", "mode": "ro"}
        # rw: attaching kprobes means writing to /sys/kernel/debug/tracing/kprobe_events
        agent.volumes["/sys/kernel/debug"] = {"bind": "/sys/kernel/debug", "mode": "rw"}
        agent.volumes["/sys/kernel/security"] = {"bind": "/sys/kernel/security", "mode": "rw"}
