tests/:
  apm_tracing_e2e/:
    test_otel.py:
      Test_Otel_Span: missing_feature (missing /e2e_otel_span endpoint on weblog)
    test_single_span.py:
      Test_SingleSpan: missing_feature (missing /e2e_otel_span endpoint on weblog)
  appsec/:
    api_security/:
      test_api_security_rc.py:
        Test_API_Security_RC_ASM_DD_processors: v2.50.0
        Test_API_Security_RC_ASM_DD_scanners: v2.50.0
        Test_API_Security_RC_ASM_processor_overrides_and_custom_scanner: irrelevant (waf does not support it yet)
      test_apisec_sampling.py:
        Test_API_Security_Sampling_Different_Endpoints: missing_feature
        Test_API_Security_Sampling_Different_Paths: missing_feature
        Test_API_Security_Sampling_Different_Status: missing_feature
        Test_API_Security_Sampling_Rate: v2.46.0
        Test_API_Security_Sampling_With_Delay: missing_feature
      test_schemas.py:
        Test_Scanners: v2.46.0
        Test_Schema_Request_Cookies: v2.46.0
        Test_Schema_Request_FormUrlEncoded_Body: v2.46.0
        Test_Schema_Request_Headers: v2.46.0
        Test_Schema_Request_Json_Body: v2.46.0
        Test_Schema_Request_Path_Parameters: v2.46.0
        Test_Schema_Request_Query_Parameters: v2.46.0
        Test_Schema_Response_Body: v2.46.0
        Test_Schema_Response_Body_env_var: missing_feature
        Test_Schema_Response_Headers: v2.46.0
    iast/:
      sink/:
        test_code_injection.py:
          TestCodeInjection: missing_feature
          TestCodeInjection_StackTrace: missing_feature
        test_command_injection.py:
          TestCommandInjection: v2.28.0
          TestCommandInjection_StackTrace: missing_feature
        test_hardcoded_passwords.py:
          Test_HardcodedPasswords: missing_feature
          Test_HardcodedPasswords_StackTrace: missing_feature
        test_hardcoded_secrets.py:
          Test_HardcodedSecrets: missing_feature
          Test_HardcodedSecretsExtended: missing_feature
          Test_HardcodedSecrets_StackTrace: missing_feature
        test_header_injection.py:
          TestHeaderInjection: v2.46.0
          TestHeaderInjectionExclusionAccessControlAllow: missing_feature
          TestHeaderInjectionExclusionContentEncoding: missing_feature
          TestHeaderInjectionExclusionPragma: missing_feature
          TestHeaderInjectionExclusionTransferEncoding: missing_feature
          TestHeaderInjection_StackTrace: missing_feature
        test_hsts_missing_header.py:
          Test_HstsMissingHeader: v2.44.0
          Test_HstsMissingHeader_StackTrace: missing_feature
        test_insecure_auth_protocol.py:
          Test_InsecureAuthProtocol: v2.49.0
          Test_InsecureAuthProtocol_StackTrace: missing_feature
        test_insecure_cookie.py:
          TestInsecureCookie: v2.39.0
          TestInsecureCookieNameFilter: missing_feature
          TestInsecureCookie_StackTrace: missing_feature
        test_ldap_injection.py:
          TestLDAPInjection: v2.36.0
          TestLDAPInjection_StackTrace: missing_feature
        test_no_httponly_cookie.py:
          TestNoHttponlyCookie: v2.39.0
          TestNoHttponlyCookieNameFilter: missing_feature
          TestNoHttponlyCookie_StackTrace: missing_feature
        test_no_samesite_cookie.py:
          TestNoSamesiteCookie: v2.39.0
          TestNoSamesiteCookieNameFilter: missing_feature
          TestNoSamesiteCookie_StackTrace: missing_feature
        test_nosql_mongodb_injection.py:
          TestNoSqlMongodbInjection: v2.47.0
          TestNoSqlMongodbInjection_StackTrace: missing_feature
        test_path_traversal.py:
          TestPathTraversal: v2.31.0
          TestPathTraversal_StackTrace: missing_feature
        test_reflection_injection.py:
          TestReflectionInjection: v2.48.0
          TestReflectionInjection_StackTrace: missing_feature
        test_sql_injection.py:
          TestSqlInjection:
             '*': v2.23.0
          TestSqlInjection_StackTrace: missing_feature
        test_ssrf.py:
          TestSSRF: v2.36.0
          TestSSRF_StackTrace: missing_feature
        test_template_injection.py:
          TestTemplateInjection: missing_feature
        test_trust_boundary_violation.py:
          Test_TrustBoundaryViolation: v2.43.0
          Test_TrustBoundaryViolation_StackTrace: missing_feature
        test_untrusted_deserialization.py:
          TestUntrustedDeserialization: missing_feature
          TestUntrustedDeserialization_StackTrace: missing_feature
        test_unvalidated_redirect.py:
          TestUnvalidatedHeader: v2.44.0
          TestUnvalidatedHeader_StackTrace: missing_feature
          TestUnvalidatedRedirect: v2.44.0
          TestUnvalidatedRedirect_StackTrace: missing_feature
        test_unvalidated_redirect_forward.py:
          TestUnvalidatedForward: missing_feature
          TestUnvalidatedForward_StackTrace: missing_feature
        test_weak_cipher.py:
          TestWeakCipher: v2.24.0
          TestWeakCipher_StackTrace: missing_feature
        test_weak_hash.py:
          TestDeduplication: v2.24.0
          TestWeakHash: v2.24.0
          TestWeakHash_StackTrace: missing_feature
        test_weak_randomness.py:
          TestWeakRandomness: v2.39.0
          TestWeakRandomness_StackTrace: missing_feature
        test_xcontent_sniffing.py:
          Test_XContentSniffing: missing_feature
          Test_XContentSniffing_StackTrace: missing_feature
        test_xpath_injection.py:
          TestXPathInjection: v2.47.0
          TestXPathInjection_StackTrace: missing_feature
        test_xss.py:
          TestXSS: missing_feature
          TestXSS_StackTrace: missing_feature
      source/:
        test_body.py:
          TestRequestBody: v2.39.0
        test_cookie_name.py:
          TestCookieName: v2.42.0
        test_cookie_value.py:
          TestCookieValue: v2.42.0
        test_graphql_resolver.py:
          TestGraphqlResolverArgument: missing_feature
        test_header_name.py:
          TestHeaderName: missing_feature
        test_header_value.py:
          TestHeaderValue:
             '*': v2.39.0
        test_kafka_key.py:
          TestKafkaKey: missing_feature
        test_kafka_value.py:
          TestKafkaValue: missing_feature
        test_multipart.py:
          TestMultipart: missing_feature
        test_parameter_name.py:
          TestParameterName: v2.28.0
        test_parameter_value.py:
          TestParameterValue: v2.28.0
        test_path.py:
          TestPath: v2.39.0
        test_path_parameter.py:
          TestPathParameter: missing_feature
        test_uri.py:
          TestURI: irrelevant
    rasp/:
      test_cmdi.py:
        Test_Cmdi_BodyJson: missing_feature
        Test_Cmdi_BodyUrlEncoded: missing_feature
        Test_Cmdi_BodyXml: missing_feature
        Test_Cmdi_Capability: missing_feature
        Test_Cmdi_Mandatory_SpanTags: missing_feature
        Test_Cmdi_Optional_SpanTags: missing_feature
        Test_Cmdi_Rules_Version: missing_feature
        Test_Cmdi_StackTrace: missing_feature
        Test_Cmdi_Telemetry: missing_feature
        Test_Cmdi_Telemetry_Variant_Tag: missing_feature
        Test_Cmdi_UrlQuery: missing_feature
        Test_Cmdi_Waf_Version: missing_feature
      test_lfi.py:
        Test_Lfi_BodyJson: v2.51.0
        Test_Lfi_BodyUrlEncoded: v2.51.0
        Test_Lfi_BodyXml: v2.51.0
        Test_Lfi_Capability: v3.3.0
        Test_Lfi_Mandatory_SpanTags: v2.52.0
        Test_Lfi_Optional_SpanTags: v2.52.0
        Test_Lfi_RC_CustomAction: missing_feature
        Test_Lfi_Rules_Version: missing_feature
        Test_Lfi_StackTrace: v2.51.0
        Test_Lfi_Telemetry: v2.51.0
        Test_Lfi_UrlQuery: v2.51.0
        Test_Lfi_Waf_Version: v3.4.1
      test_shi.py:
        Test_Shi_BodyJson: v3.2.0
        Test_Shi_BodyUrlEncoded: v3.2.0
        Test_Shi_BodyXml: v3.2.0
        Test_Shi_Capability: v3.3.0
        Test_Shi_Mandatory_SpanTags: v3.2.0
        Test_Shi_Optional_SpanTags: v3.2.0
        Test_Shi_Rules_Version: v3.5.0
        Test_Shi_StackTrace: v3.2.0
        Test_Shi_Telemetry: v3.3.0
  serverless/:
    span_pointers/:
      aws/:
        test_s3_span_pointers.py:
          Test_CopyObject: missing_feature
          Test_MultipartUpload: missing_feature
          Test_PutObject: missing_feature
  stats/:
    test_miscs.py:
      Test_Miscs: missing_feature
  test_config_consistency.py:
    Test_Config_ClientIPHeaderEnabled_False: v3.6.1
    Test_Config_ClientIPHeader_Configured: v3.4.1
    Test_Config_ClientIPHeader_Precedence: v3.4.1
    Test_Config_ClientTagQueryString_Configured: missing_feature (configuration DNE)
    Test_Config_ClientTagQueryString_Empty: v3.5.0
    Test_Config_HttpClientErrorStatuses_Default: v3.5.0
    Test_Config_HttpClientErrorStatuses_FeatureFlagCustom: v3.5.0
    Test_Config_HttpServerErrorStatuses_Default: v3.5.0
    Test_Config_HttpServerErrorStatuses_FeatureFlagCustom: v3.5.0
    Test_Config_IntegrationEnabled_False: v3.5.0
    Test_Config_IntegrationEnabled_True: v3.5.0
    Test_Config_ObfuscationQueryStringRegexp_Configured: v3.4.1
    Test_Config_ObfuscationQueryStringRegexp_Empty: v3.4.1
    Test_Config_UnifiedServiceTagging_CustomService: v3.3.0
    Test_Config_UnifiedServiceTagging_Default: v3.3.0
  test_data_integrity.py:
    Test_LibraryHeaders: v2.46.0
  test_distributed.py:
    Test_DistributedHttp: missing_feature
    Test_Span_Links_Flags_From_Conflicting_Contexts: missing_feature (implementation specs have not been determined)
    Test_Span_Links_From_Conflicting_Contexts: missing_feature
    Test_Span_Links_From_Conflicting_Contexts_Datadog_Precedence: missing_feature
    Test_Span_Links_Omit_Tracestate_From_Conflicting_Contexts: missing_feature (implementation specs have not been determined)
  test_identify.py:
    Test_Basic: v2.7.0
    Test_Propagate: v2.27.0
    Test_Propagate_Legacy: v2.26.0
  test_library_conf.py:
    Test_HeaderTags: v2.27.0
    Test_HeaderTags_Colon_Leading: v2.1.0
    Test_HeaderTags_Colon_Trailing: v3.0.0
    Test_HeaderTags_DynamicConfig: missing_feature
    Test_HeaderTags_Long: v2.1.0
    Test_HeaderTags_Short: v2.1.0
    Test_HeaderTags_Whitespace_Header: v2.1.0
    Test_HeaderTags_Whitespace_Tag: v3.0.0
    Test_HeaderTags_Whitespace_Val_Long: v2.1.0
    Test_HeaderTags_Whitespace_Val_Short: v2.1.0
  test_profiling.py:
    Test_Profile:
      "*": v1.0  # real version not known
      uds: missing_feature (to be confirmed)
  test_scrubbing.py:
    Test_UrlField: v2.29.0
    Test_UrlQuery: v2.13.0
  test_semantic_conventions.py:
    Test_MetricsStandardTags: v2.6.0
  test_span_events.py: missing_feature (Weblog `/add_event` not implemented)
  test_standard_tags.py:
    Test_StandardTagsClientIp: v2.26.0
    Test_StandardTagsMethod: v2.0.0
    Test_StandardTagsRoute: v2.13.0
    Test_StandardTagsStatusCode: v2.0.0
    Test_StandardTagsUrl: v2.13.0
    Test_StandardTagsUserAgent: v2.13.0
  test_telemetry.py:
    Test_DependencyEnable: v2.35.0
    Test_Log_Generation: missing_feature
    Test_MessageBatch: v2.35.0
    Test_Metric_Generation_Disabled: v2.35.0
    Test_Metric_Generation_Enabled: v2.35.0
    Test_ProductsDisabled: v2.12.0
    Test_Telemetry: v2.12.0
    Test_TelemetrySCAEnvVar: missing_feature
    Test_TelemetryV2: v2.35.0
