name: "Push to TestOptim"
description: "Push test runs to DataDog Test Optimization"
inputs:
  datadog_site:
    description: Which DataDog site shoud be used
    default: datadoghq.com
  datadog_api_key:
    description: "A valid DD_API_KEY"
    default: ""
  ci_environment:
    description: "CI environment running the tests (dev/prod/custom), used for Test Optimization tagging"
    default: ""
  dd_sts_policy:
    description: "dd-sts policy to use to get a datadog API key (required if datadog_api_key is not set)"
    default: ""

runs:
  using: composite
  steps:
    - name: Skip for dependabot
      if: github.event.pull_request.user.login == 'dependabot[bot]'
      shell: bash
      run: echo "Skipping TestOptim push for dependabot PRs"

    - name: Install datadog-ci
      if: github.event.pull_request.user.login != 'dependabot[bot]' && (inputs.datadog_api_key != '' || inputs.dd_sts_policy != '')
      shell: bash
      run: npm install -g @datadog/datadog-ci || sleep 60 && npm install -g @datadog/datadog-ci

    - name: checkout owner repo
      if: github.event.pull_request.user.login != 'dependabot[bot]' && (inputs.datadog_api_key != '' || inputs.dd_sts_policy != '')
      uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      with:
        path: repo

    - name: Get Datadog credentials
      id: dd-sts
      if: inputs.dd_sts_policy != ''
      uses: DataDog/dd-sts-action@2e8187910199bd93129520183c093e19aa585c75 # v1.0.0
      with:
        policy: ${{ inputs.dd_sts_policy }}

    # https://docs.datadoghq.com/tests/setup/junit_xml/?tab=linux
    - name: Push results
      if: github.event.pull_request.user.login != 'dependabot[bot]' && (inputs.datadog_api_key != '' || inputs.dd_sts_policy != '')
      shell: bash
      run: |
        cd repo
        datadog-ci junit upload \
          ../logs*/reportJunit.xml \
          --service system-tests \
          --env ci \
          --verbose \
          --xpath-tag "test.codeowners=/testcase/properties/property[@name='test.codeowners']"
      env:
        DATADOG_SITE: ${{ inputs.datadog_site }}
        DATADOG_API_KEY:  ${{ inputs.datadog_api_key != '' && inputs.datadog_api_key || steps.dd-sts.outputs.api_key }}
        DD_TAGS: ${{ inputs.ci_environment != '' && format('test.configuration.ci_environment:{0}', inputs.ci_environment) || '' }}
