name: Lib injection test runner
description: "Lib injection tests runner"

inputs:
  docker-registry:
    description: Docker registry to be used to push weblog images
    required: true
  docker-registry-username:
    description: username for Docker registry
    required: true
  docker-registry-password:
    description: password for Docker registry
    required: true
runs:
  using: composite
  steps:
      - name: Checkout system tests
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # 2.3.4
        with:
          repository: 'DataDog/system-tests'
          path: './system-tests'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8 # 2.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6 # 2.0.0
        with: 
          install: true
          config-inline: |
            [worker.oci]
              max-parallelism = 1

      - name: Log in to the Container registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # 2.0.0
        with:
          registry: ${{ inputs.docker-registry }}
          username: ${{ inputs.docker-registry-username }}
          password: ${{ inputs.docker-registry-password}}
      
      - name: Build injection image
        shell: bash
        run: |
          cd system-tests   
          ./lib-injection/execFunction.sh build-and-push-test-app-image 
          ./lib-injection/build.sh
 
      - name: Run lib injection tests
        shell: bash
        run: |
          cd system-tests   
          ./lib-injection/run-lib-injection.sh

      - name: Compress lib injection logs
        shell: bash
        if: ${{ always() }}
        run: cd system-tests && tar -czvf ../artifact.tar.gz $(ls | grep logs)

      - name: Upload lib injection logs
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # 2.3.1
        if: ${{ always() }}
        with:
          name: library-injection_${{ env.TEST_LIBRARY }}_${{ matrix.weblog-variant }}_${{ matrix.lib-injection-connection }}_${{ matrix.lib-injection-use-admission-controller }}_${{ env.DOCKER_IMAGE_TAG}}
          path: artifact.tar.gz