name: Lib injection test runner
description: "Lib injection tests runner"

inputs:
  docker-registry:
    description: Docker registry to be used to push weblog images
    required: true
  docker-registry-username:
    description: username for Docker registry
    required: true
  docker-registry-password:
    description: password for Docker registry
    required: true
  test-script:
    description: test script to run
    required: true
runs:
  using: composite
  steps:
      - name: Checkout system tests
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # 3.3.0
        with:
          repository: 'DataDog/system-tests'
          path: './system-tests'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8  # 2.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325 # 2.2.1
        with:
          install: true
          config-inline: |
            [worker.oci]
              max-parallelism = 1

      - name: Log in to the Container registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # 2.1.0
        with:
          registry: ${{ inputs.docker-registry }}
          username: ${{ inputs.docker-registry-username }}
          password: ${{ inputs.docker-registry-password}}

      - name: Build injection image
        shell: bash
        run: |
          cd system-tests
          ./lib-injection/execFunction.sh build-and-push-test-app-image
          ./lib-injection/build.sh

      - name: Run lib injection tests
        shell: bash
        run: |
          cd system-tests
          ${{ inputs.test-script }}

      - name: Debug kubernetes cluster info
        shell: bash
        if: ${{ always() }}
        run: |
          cd system-tests
          ./lib-injection/execFunction.sh $LIBRARY_INJECTION_ADMISSION_CONTROLLER print-debug-info

      - name: Compress lib injection logs
        shell: bash
        if: ${{ always() }}
        run: cd system-tests && tar -czvf ../artifact.tar.gz $(ls | grep logs)

      - name: Upload lib injection logs
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # 3.1.2
        if: ${{ always() }}
        with:
          name: ${{ env.MODE }}-lib-injection_${{ env.TEST_LIBRARY }}_${{ matrix.weblog-variant }}_${{ matrix.lib-injection-connection }}_${{ matrix.lib-injection-use-admission-controller }}_${{ env.DOCKER_IMAGE_TAG}}
          path: artifact.tar.gz
