# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: apm_test_client.proto for package ''

require 'grpc'
require 'apm_test_client_pb'

module APMClient
  # Interface of APM clients to be used for shared testing.
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'APMClient'

    rpc :StartSpan, ::StartSpanArgs, ::StartSpanReturn
    rpc :FinishSpan, ::FinishSpanArgs, ::FinishSpanReturn
    rpc :SpanSetMeta, ::SpanSetMetaArgs, ::SpanSetMetaReturn
    rpc :SpanSetMetric, ::SpanSetMetricArgs, ::SpanSetMetricReturn
    rpc :SpanSetError, ::SpanSetErrorArgs, ::SpanSetErrorReturn
    rpc :InjectHeaders, ::InjectHeadersArgs, ::InjectHeadersReturn
    rpc :FlushSpans, ::FlushSpansArgs, ::FlushSpansReturn
    rpc :FlushTraceStats, ::FlushTraceStatsArgs, ::FlushTraceStatsReturn
  end

  Stub = Service.rpc_stub_class
end
