PREFIX = "http.request.headers."

HEADER_VAL_BASIC = "val"

HEADER_NAME_SHORT = "header1"
CONFIG_SHORT = "header1"
TAG_SHORT = "http.request.headers.header1"

HEADER_NAME_LONG = "header2"
CONFIG_LONG = "header2:mapped-header"
TAG_LONG = "mapped-header"

CONFIG_WILDCARD = "*"
REQUEST_WILDCARD_TAG_PREFIX = "http.request.headers."
RESPONSE_WILDCARD_TAG_PREFIX = "http.response.headers."

HEADER_NAME_WHITESPACE_HEADER = "header3"
CONFIG_WHITESPACE_HEADER = " header3 "
TAG_WHITESPACE_HEADER = "http.request.headers.header3"

HEADER_NAME_WHITESPACE_TAG = "header4"
CONFIG_WHITESPACE_TAG = "header4: t a g "
TAG_WHITESPACE_TAG = "t a g"

HEADER_NAME_WHITESPACE_VAL_SHORT = "header5"
CONFIG_WHITESPACE_VAL_SHORT = "header5"
TAG_WHITESPACE_VAL_SHORT = "http.request.headers.header5"
HEADER_VAL_WHITESPACE_VAL_SHORT = " v a l "

HEADER_NAME_WHITESPACE_VAL_LONG = "header6"
CONFIG_WHITESPACE_VAL_LONG = "header6:tag"
TAG_WHITESPACE_VAL_LONG = "tag"
HEADER_VAL_WHITESPACE_VAL_LONG = " v a l "

VALID_CONFIGS = (
    CONFIG_SHORT,
    CONFIG_LONG,
    CONFIG_WHITESPACE_HEADER,
    CONFIG_WHITESPACE_TAG,
    CONFIG_WHITESPACE_VAL_SHORT,
    CONFIG_WHITESPACE_VAL_LONG,
)

HEADER_NAME_COLON_LEADING = "header7"
CONFIG_COLON_LEADING = ":header7"
TAG_COLON_LEADING = None

HEADER_NAME_COLON_TRAILING = "header8"
CONFIG_COLON_TRAILING = "header8:"
TAG_COLON_TRAILING = None

INVALID_CONFIGS = (CONFIG_COLON_LEADING, CONFIG_COLON_TRAILING)
