# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/apm_test_client.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cprotos/apm_test_client.proto\"\xc5\x01\n\rStartSpanArgs\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x07service\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tparent_id\x18\x03 \x01(\x04H\x01\x88\x01\x01\x12\x15\n\x08resource\x18\x04 \x01(\tH\x02\x88\x01\x01\x12\x11\n\x04type\x18\x05 \x01(\tH\x03\x88\x01\x01\x12\x13\n\x06origin\x18\x06 \x01(\tH\x04\x88\x01\x01\x42\n\n\x08_serviceB\x0c\n\n_parent_idB\x0b\n\t_resourceB\x07\n\x05_typeB\t\n\x07_origin\"4\n\x0fStartSpanReturn\x12\x0f\n\x07span_id\x18\x01 \x01(\x04\x12\x10\n\x08trace_id\x18\x02 \x01(\x04\"\x1c\n\x0e\x46inishSpanArgs\x12\n\n\x02id\x18\x01 \x01(\x04\"\x12\n\x10\x46inishSpanReturn\">\n\x0fSpanSetMetaArgs\x12\x0f\n\x07span_id\x18\x01 \x01(\x04\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"\x13\n\x11SpanSetMetaReturn\"@\n\x11SpanSetMetricArgs\x12\x0f\n\x07span_id\x18\x01 \x01(\x04\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x02\"\x15\n\x13SpanSetMetricReturn\"\x10\n\x0e\x46lushSpansArgs\"\x12\n\x10\x46lushSpansReturn\"\x15\n\x13\x46lushTraceStatsArgs\"\x17\n\x15\x46lushTraceStatsReturn2\xdb\x02\n\tAPMClient\x12/\n\tStartSpan\x12\x0e.StartSpanArgs\x1a\x10.StartSpanReturn\"\x00\x12\x32\n\nFinishSpan\x12\x0f.FinishSpanArgs\x1a\x11.FinishSpanReturn\"\x00\x12\x35\n\x0bSpanSetMeta\x12\x10.SpanSetMetaArgs\x1a\x12.SpanSetMetaReturn\"\x00\x12;\n\rSpanSetMetric\x12\x12.SpanSetMetricArgs\x1a\x14.SpanSetMetricReturn\"\x00\x12\x32\n\nFlushSpans\x12\x0f.FlushSpansArgs\x1a\x11.FlushSpansReturn\"\x00\x12\x41\n\x0f\x46lushTraceStats\x12\x14.FlushTraceStatsArgs\x1a\x16.FlushTraceStatsReturn\"\x00\x62\x06proto3')



_STARTSPANARGS = DESCRIPTOR.message_types_by_name['StartSpanArgs']
_STARTSPANRETURN = DESCRIPTOR.message_types_by_name['StartSpanReturn']
_FINISHSPANARGS = DESCRIPTOR.message_types_by_name['FinishSpanArgs']
_FINISHSPANRETURN = DESCRIPTOR.message_types_by_name['FinishSpanReturn']
_SPANSETMETAARGS = DESCRIPTOR.message_types_by_name['SpanSetMetaArgs']
_SPANSETMETARETURN = DESCRIPTOR.message_types_by_name['SpanSetMetaReturn']
_SPANSETMETRICARGS = DESCRIPTOR.message_types_by_name['SpanSetMetricArgs']
_SPANSETMETRICRETURN = DESCRIPTOR.message_types_by_name['SpanSetMetricReturn']
_FLUSHSPANSARGS = DESCRIPTOR.message_types_by_name['FlushSpansArgs']
_FLUSHSPANSRETURN = DESCRIPTOR.message_types_by_name['FlushSpansReturn']
_FLUSHTRACESTATSARGS = DESCRIPTOR.message_types_by_name['FlushTraceStatsArgs']
_FLUSHTRACESTATSRETURN = DESCRIPTOR.message_types_by_name['FlushTraceStatsReturn']
StartSpanArgs = _reflection.GeneratedProtocolMessageType('StartSpanArgs', (_message.Message,), {
  'DESCRIPTOR' : _STARTSPANARGS,
  '__module__' : 'protos.apm_test_client_pb2'
  # @@protoc_insertion_point(class_scope:StartSpanArgs)
  })
_sym_db.RegisterMessage(StartSpanArgs)

StartSpanReturn = _reflection.GeneratedProtocolMessageType('StartSpanReturn', (_message.Message,), {
  'DESCRIPTOR' : _STARTSPANRETURN,
  '__module__' : 'protos.apm_test_client_pb2'
  # @@protoc_insertion_point(class_scope:StartSpanReturn)
  })
_sym_db.RegisterMessage(StartSpanReturn)

FinishSpanArgs = _reflection.GeneratedProtocolMessageType('FinishSpanArgs', (_message.Message,), {
  'DESCRIPTOR' : _FINISHSPANARGS,
  '__module__' : 'protos.apm_test_client_pb2'
  # @@protoc_insertion_point(class_scope:FinishSpanArgs)
  })
_sym_db.RegisterMessage(FinishSpanArgs)

FinishSpanReturn = _reflection.GeneratedProtocolMessageType('FinishSpanReturn', (_message.Message,), {
  'DESCRIPTOR' : _FINISHSPANRETURN,
  '__module__' : 'protos.apm_test_client_pb2'
  # @@protoc_insertion_point(class_scope:FinishSpanReturn)
  })
_sym_db.RegisterMessage(FinishSpanReturn)

SpanSetMetaArgs = _reflection.GeneratedProtocolMessageType('SpanSetMetaArgs', (_message.Message,), {
  'DESCRIPTOR' : _SPANSETMETAARGS,
  '__module__' : 'protos.apm_test_client_pb2'
  # @@protoc_insertion_point(class_scope:SpanSetMetaArgs)
  })
_sym_db.RegisterMessage(SpanSetMetaArgs)

SpanSetMetaReturn = _reflection.GeneratedProtocolMessageType('SpanSetMetaReturn', (_message.Message,), {
  'DESCRIPTOR' : _SPANSETMETARETURN,
  '__module__' : 'protos.apm_test_client_pb2'
  # @@protoc_insertion_point(class_scope:SpanSetMetaReturn)
  })
_sym_db.RegisterMessage(SpanSetMetaReturn)

SpanSetMetricArgs = _reflection.GeneratedProtocolMessageType('SpanSetMetricArgs', (_message.Message,), {
  'DESCRIPTOR' : _SPANSETMETRICARGS,
  '__module__' : 'protos.apm_test_client_pb2'
  # @@protoc_insertion_point(class_scope:SpanSetMetricArgs)
  })
_sym_db.RegisterMessage(SpanSetMetricArgs)

SpanSetMetricReturn = _reflection.GeneratedProtocolMessageType('SpanSetMetricReturn', (_message.Message,), {
  'DESCRIPTOR' : _SPANSETMETRICRETURN,
  '__module__' : 'protos.apm_test_client_pb2'
  # @@protoc_insertion_point(class_scope:SpanSetMetricReturn)
  })
_sym_db.RegisterMessage(SpanSetMetricReturn)

FlushSpansArgs = _reflection.GeneratedProtocolMessageType('FlushSpansArgs', (_message.Message,), {
  'DESCRIPTOR' : _FLUSHSPANSARGS,
  '__module__' : 'protos.apm_test_client_pb2'
  # @@protoc_insertion_point(class_scope:FlushSpansArgs)
  })
_sym_db.RegisterMessage(FlushSpansArgs)

FlushSpansReturn = _reflection.GeneratedProtocolMessageType('FlushSpansReturn', (_message.Message,), {
  'DESCRIPTOR' : _FLUSHSPANSRETURN,
  '__module__' : 'protos.apm_test_client_pb2'
  # @@protoc_insertion_point(class_scope:FlushSpansReturn)
  })
_sym_db.RegisterMessage(FlushSpansReturn)

FlushTraceStatsArgs = _reflection.GeneratedProtocolMessageType('FlushTraceStatsArgs', (_message.Message,), {
  'DESCRIPTOR' : _FLUSHTRACESTATSARGS,
  '__module__' : 'protos.apm_test_client_pb2'
  # @@protoc_insertion_point(class_scope:FlushTraceStatsArgs)
  })
_sym_db.RegisterMessage(FlushTraceStatsArgs)

FlushTraceStatsReturn = _reflection.GeneratedProtocolMessageType('FlushTraceStatsReturn', (_message.Message,), {
  'DESCRIPTOR' : _FLUSHTRACESTATSRETURN,
  '__module__' : 'protos.apm_test_client_pb2'
  # @@protoc_insertion_point(class_scope:FlushTraceStatsReturn)
  })
_sym_db.RegisterMessage(FlushTraceStatsReturn)

_APMCLIENT = DESCRIPTOR.services_by_name['APMClient']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STARTSPANARGS._serialized_start=33
  _STARTSPANARGS._serialized_end=230
  _STARTSPANRETURN._serialized_start=232
  _STARTSPANRETURN._serialized_end=284
  _FINISHSPANARGS._serialized_start=286
  _FINISHSPANARGS._serialized_end=314
  _FINISHSPANRETURN._serialized_start=316
  _FINISHSPANRETURN._serialized_end=334
  _SPANSETMETAARGS._serialized_start=336
  _SPANSETMETAARGS._serialized_end=398
  _SPANSETMETARETURN._serialized_start=400
  _SPANSETMETARETURN._serialized_end=419
  _SPANSETMETRICARGS._serialized_start=421
  _SPANSETMETRICARGS._serialized_end=485
  _SPANSETMETRICRETURN._serialized_start=487
  _SPANSETMETRICRETURN._serialized_end=508
  _FLUSHSPANSARGS._serialized_start=510
  _FLUSHSPANSARGS._serialized_end=526
  _FLUSHSPANSRETURN._serialized_start=528
  _FLUSHSPANSRETURN._serialized_end=546
  _FLUSHTRACESTATSARGS._serialized_start=548
  _FLUSHTRACESTATSARGS._serialized_end=569
  _FLUSHTRACESTATSRETURN._serialized_start=571
  _FLUSHTRACESTATSRETURN._serialized_end=594
  _APMCLIENT._serialized_start=597
  _APMCLIENT._serialized_end=944
# @@protoc_insertion_point(module_scope)
