stages:
  - SCENARIOS

.base_job_aws:
  image: registry.ddbuild.io/images/ci_docker_base
  tags: ["arch:amd64"]
  script:
    - echo "WEBLOG: $WEBLOG"
    - echo "SCENARIO: $SCENARIO"
    - echo "VIRTUAL_MACHINE: $VIRTUAL_MACHINE"