stages:
  - K8S_LIB_INJECTION

.k8s_lib_injection_base:
  image: registry.ddbuild.io/ci/libdatadog-build/system-tests:48436362
  tags: [ "runner:docker" ]
  stage: K8S_LIB_INJECTION
  allow_failure: false
  #rules:
  #- if: $PARENT_PIPELINE_SOURCE == "schedule"
  #  when: always
  #- when: manual
  #  allow_failure: true
  variables:
    TEST_LIBRARY: "xyz"
    K8S_WEBLOG: "xyz"
    K8S_WEBLOG_IMG: "xyz"
    K8S_SCENARIO: "xyz"
    K8S_LIB_INIT_IMG: "xyz"
    K8S_CLUSTER_VERSION: "xyz"
  script:
    - ./build.sh -i runner # rebuild runner in case there were changes
    - source venv/bin/activate
    - python --version
    - pip freeze
    - ./run.sh ${K8S_SCENARIO} --k8s-library ${TEST_LIBRARY} --k8s-weblog ${K8S_WEBLOG} --k8s-weblog-img ${K8S_WEBLOG_IMG} --k8s-lib-init-img ${K8S_LIB_INIT_IMG} --k8s-cluster-version ${K8S_CLUSTER_VERSION} --report-run-url $CI_JOB_URL --report-environment $ONBOARDING_FILTER_ENV
  after_script: |
    mkdir -p reports
    cp -R logs_*/ reports/
    kind delete clusters --all || true
    if [ "$CI_COMMIT_BRANCH" = "main" ]; then
      for folder in reports/logs*/ ; do
        echo "Checking folder: ${folder}"
         for filename in ./${folder}feature_parity.json; do
           if [ -e ${filename} ]
           then
              echo "Processing report: ${filename}"
             curl -X POST ${FP_IMPORT_URL} --fail --header "Content-Type: application/json" --header "FP_API_KEY: ${FP_API_KEY}" --data "@${filename}" --include
           fi
        done
      done
      fi
  needs:
    - job: configure_env
      artifacts: true
  artifacts:
    when: always
    paths:
      - reports/

configure_env:
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/test-infra-definitions/runner:6dd143866d67
  tags:
  - arch:amd64
  stage: K8S_LIB_INJECTION
  dependencies: []
  allow_failure: false
  rules:
  - if: $CI_PIPELINE_SOURCE == "schedule"
    when: always
  - if: $PARENT_PIPELINE_SOURCE == "schedule"
    when: always
  - when: manual
    allow_failure: true
  script:
  - export FP_IMPORT_URL=$(aws ssm get-parameter --region us-east-1 --name ci.system-tests.fp-import-url
    --with-decryption --query "Parameter.Value" --out text)
  - export FP_API_KEY=$(aws ssm get-parameter --region us-east-1 --name ci.system-tests.fp-api-key
    --with-decryption --query "Parameter.Value" --out text)
  - echo "FP_IMPORT_URL=${FP_IMPORT_URL}" >> fpd.env
  - echo "FP_API_KEY=${FP_API_KEY}" >> fpd.env
  - export DD_API_KEY_ONBOARDING=$(aws ssm get-parameter --region us-east-1 --name ci.${CI_PROJECT_NAME}.dd-api-key-onboarding --with-decryption --query "Parameter.Value" --out text) >> fpd.env
  - export DD_APP_KEY_ONBOARDING=$(aws ssm get-parameter --region us-east-1 --name ci.${CI_PROJECT_NAME}.dd-app-key-onboarding --with-decryption --query "Parameter.Value" --out text) >> fpd.env

  artifacts:
    reports:
      dotenv: fpd.env

k8s_java:
  extends: .k8s_lib_injection_base
  variables:
    TEST_LIBRARY: "java"
  parallel:
      matrix:
        - K8S_WEBLOG: [dd-djm-spark-test-app ]
          K8S_WEBLOG_IMG: [ghcr.io/datadog/system-tests/dd-djm-spark-test-app:latest]
          K8S_SCENARIO: [K8S_LIB_INJECTION_SPARK_DJM]
          K8S_LIB_INIT_IMG: ["gcr.io/datadoghq/dd-lib-java-init:latest", "ghcr.io/datadog/dd-trace-java/dd-lib-java-init:latest_snapshot"]
          K8S_CLUSTER_VERSION: ['7.57.0', '7.59.0']
        - K8S_WEBLOG: [dd-lib-java-init-test-app]
          K8S_WEBLOG_IMG: [ghcr.io/datadog/system-tests/dd-lib-java-init-test-app:latest]
          K8S_SCENARIO: [K8S_LIB_INJECTION, K8S_LIB_INJECTION_UDS, K8S_LIB_INJECTION_NO_AC, K8S_LIB_INJECTION_NO_AC_UDS, K8S_LIB_INJECTION_PROFILING_DISABLED, K8S_LIB_INJECTION_PROFILING_ENABLED, K8S_LIB_INJECTION_PROFILING_OVERRIDE, K8S_LIB_INJECTION_OPERATOR]
          K8S_LIB_INIT_IMG: ["gcr.io/datadoghq/dd-lib-java-init:latest", "ghcr.io/datadog/dd-trace-java/dd-lib-java-init:latest_snapshot"]
          K8S_CLUSTER_VERSION: ['7.56.2', '7.57.0', '7.59.0']

k8s_dotnet:
  extends: .k8s_lib_injection_base
  variables:
    TEST_LIBRARY: "dotnet"
  parallel:
      matrix:
        - K8S_WEBLOG: [dd-lib-dotnet-init-test-app]
          K8S_WEBLOG_IMG: [ghcr.io/datadog/system-tests/dd-lib-dotnet-init-test-app:latest]
          K8S_SCENARIO: [K8S_LIB_INJECTION, K8S_LIB_INJECTION_UDS, K8S_LIB_INJECTION_NO_AC, K8S_LIB_INJECTION_NO_AC_UDS, K8S_LIB_INJECTION_PROFILING_DISABLED, K8S_LIB_INJECTION_PROFILING_ENABLED, K8S_LIB_INJECTION_PROFILING_OVERRIDE, K8S_LIB_INJECTION_OPERATOR]
          K8S_LIB_INIT_IMG: ["gcr.io/datadoghq/dd-lib-dotnet-init:latest", "ghcr.io/datadog/dd-trace-dotnet/dd-lib-dotnet-init:latest_snapshot"]
          K8S_CLUSTER_VERSION: ['7.56.2', '7.57.0', '7.59.0']

k8s_nodejs:
  extends: .k8s_lib_injection_base
  variables:
    TEST_LIBRARY: "nodejs"
  parallel:
      matrix:
        - K8S_WEBLOG: [sample-app]
          K8S_WEBLOG_IMG: [ghcr.io/datadog/system-tests/sample-app:latest]
          K8S_SCENARIO: [K8S_LIB_INJECTION, K8S_LIB_INJECTION_UDS, K8S_LIB_INJECTION_NO_AC, K8S_LIB_INJECTION_NO_AC_UDS, K8S_LIB_INJECTION_PROFILING_DISABLED, K8S_LIB_INJECTION_PROFILING_ENABLED, K8S_LIB_INJECTION_PROFILING_OVERRIDE, K8S_LIB_INJECTION_OPERATOR]
          K8S_LIB_INIT_IMG: ["gcr.io/datadoghq/dd-lib-js-init:latest", "ghcr.io/datadog/dd-trace-js/dd-lib-js-init:latest_snapshot"]
          K8S_CLUSTER_VERSION: ['7.56.2', '7.57.0', '7.59.0']

k8s_python:
  extends: .k8s_lib_injection_base
  variables:
    TEST_LIBRARY: "python"
  parallel:
      matrix:
        - K8S_WEBLOG: [dd-lib-python-init-test-django]
          K8S_WEBLOG_IMG: [ghcr.io/datadog/system-tests/dd-lib-python-init-test-django:latest]
          K8S_SCENARIO: [K8S_LIB_INJECTION, K8S_LIB_INJECTION_UDS, K8S_LIB_INJECTION_NO_AC, K8S_LIB_INJECTION_NO_AC_UDS, K8S_LIB_INJECTION_PROFILING_DISABLED, K8S_LIB_INJECTION_PROFILING_ENABLED, K8S_LIB_INJECTION_PROFILING_OVERRIDE, K8S_LIB_INJECTION_OPERATOR]
          K8S_LIB_INIT_IMG: ["gcr.io/datadoghq/dd-lib-python-init:latest", "ghcr.io/datadog/dd-trace-py/dd-lib-python-init:latest_snapshot"]
          K8S_CLUSTER_VERSION: ['7.56.2', '7.57.0', '7.59.0']
        - K8S_WEBLOG: [dd-lib-python-init-test-django-gunicorn]
          K8S_WEBLOG_IMG: [ghcr.io/datadog/system-tests/dd-lib-python-init-test-django-gunicorn:latest]
          K8S_SCENARIO: [K8S_LIB_INJECTION, K8S_LIB_INJECTION_PROFILING_ENABLED]
          K8S_LIB_INIT_IMG: ["gcr.io/datadoghq/dd-lib-python-init:latest", "ghcr.io/datadog/dd-trace-py/dd-lib-python-init:latest_snapshot"]
          K8S_CLUSTER_VERSION: ['7.56.2', '7.57.0', '7.59.0']
        - K8S_WEBLOG: [dd-lib-python-init-test-django-gunicorn-alpine]
          K8S_WEBLOG_IMG: [ghcr.io/datadog/system-tests/dd-lib-python-init-test-django-gunicorn-alpine:latest]
          K8S_SCENARIO: [K8S_LIB_INJECTION, K8S_LIB_INJECTION_PROFILING_ENABLED]
          K8S_LIB_INIT_IMG: ["gcr.io/datadoghq/dd-lib-python-init:latest", "ghcr.io/datadog/dd-trace-py/dd-lib-python-init:latest_snapshot"]
          K8S_CLUSTER_VERSION: ['7.56.2', '7.57.0', '7.59.0']
        - K8S_WEBLOG: [dd-lib-python-init-test-django-unsupported-package-force]
          K8S_WEBLOG_IMG: [ghcr.io/datadog/system-tests/dd-lib-python-init-test-django-unsupported-package-force:latest]
          K8S_SCENARIO: [K8S_LIB_INJECTION, K8S_LIB_INJECTION_PROFILING_ENABLED]
          K8S_LIB_INIT_IMG: ["gcr.io/datadoghq/dd-lib-python-init:latest", "ghcr.io/datadog/dd-trace-py/dd-lib-python-init:latest_snapshot"]
          K8S_CLUSTER_VERSION: ['7.56.2', '7.57.0', '7.59.0']
        - K8S_WEBLOG: [dd-lib-python-init-test-django-uvicorn]
          K8S_WEBLOG_IMG: [ghcr.io/datadog/system-tests/dd-lib-python-init-test-django-uvicorn:latest]
          K8S_SCENARIO: [K8S_LIB_INJECTION, K8S_LIB_INJECTION_PROFILING_ENABLED]
          K8S_LIB_INIT_IMG: ["gcr.io/datadoghq/dd-lib-python-init:latest", "ghcr.io/datadog/dd-trace-py/dd-lib-python-init:latest_snapshot"]
          K8S_CLUSTER_VERSION: ['7.56.2', '7.57.0', '7.59.0']
        - K8S_WEBLOG: [dd-lib-python-init-test-protobuf-old]
          K8S_WEBLOG_IMG: [ghcr.io/datadog/system-tests/dd-lib-python-init-test-protobuf-old:latest]
          K8S_SCENARIO: [K8S_LIB_INJECTION, K8S_LIB_INJECTION_PROFILING_ENABLED]
          K8S_LIB_INIT_IMG: ["gcr.io/datadoghq/dd-lib-python-init:latest", "ghcr.io/datadog/dd-trace-py/dd-lib-python-init:latest_snapshot"]
          K8S_CLUSTER_VERSION: ['7.56.2', '7.57.0', '7.59.0']
        - K8S_WEBLOG: [dd-lib-python-init-test-django-preinstalled]
          K8S_WEBLOG_IMG: [ghcr.io/datadog/system-tests/dd-lib-python-init-test-django-preinstalled:latest]
          K8S_SCENARIO: [K8S_LIB_INJECTION, K8S_LIB_INJECTION_UDS, K8S_LIB_INJECTION_NO_AC, K8S_LIB_INJECTION_NO_AC_UDS]
          K8S_LIB_INIT_IMG: ["gcr.io/datadoghq/dd-lib-python-init:latest", "ghcr.io/datadog/dd-trace-py/dd-lib-python-init:latest_snapshot"]
          K8S_CLUSTER_VERSION: ['7.56.2', '7.57.0', '7.59.0']

k8s_ruby:
  extends: .k8s_lib_injection_base
  variables:
    TEST_LIBRARY: "ruby"
  parallel:
      matrix:
        - K8S_WEBLOG: [dd-lib-ruby-init-test-rails]
          K8S_WEBLOG_IMG: [ghcr.io/datadog/system-tests/dd-lib-ruby-init-test-rails:latest]
          K8S_SCENARIO: [K8S_LIB_INJECTION, K8S_LIB_INJECTION_UDS, K8S_LIB_INJECTION_NO_AC, K8S_LIB_INJECTION_NO_AC_UDS, K8S_LIB_INJECTION_PROFILING_DISABLED, K8S_LIB_INJECTION_PROFILING_ENABLED, K8S_LIB_INJECTION_PROFILING_OVERRIDE, K8S_LIB_INJECTION_OPERATOR]
          K8S_LIB_INIT_IMG: ["gcr.io/datadoghq/dd-lib-ruby-init:latest", "ghcr.io/datadog/dd-trace-rb/dd-lib-ruby-init:latest_snapshot"]
          K8S_CLUSTER_VERSION: ['7.56.2', '7.57.0', '7.59.0']
        - K8S_WEBLOG: [dd-lib-ruby-init-test-rails-explicit]
          K8S_WEBLOG_IMG: [ghcr.io/datadog/system-tests/dd-lib-ruby-init-test-rails-explicit:latest]
          K8S_SCENARIO: [K8S_LIB_INJECTION, K8S_LIB_INJECTION_UDS, K8S_LIB_INJECTION_NO_AC, K8S_LIB_INJECTION_NO_AC_UDS, K8S_LIB_INJECTION_PROFILING_DISABLED, K8S_LIB_INJECTION_PROFILING_ENABLED, K8S_LIB_INJECTION_PROFILING_OVERRIDE]
          K8S_LIB_INIT_IMG: ["gcr.io/datadoghq/dd-lib-ruby-init:latest", "ghcr.io/datadog/dd-trace-rb/dd-lib-ruby-init:latest_snapshot"]
          K8S_CLUSTER_VERSION: ['7.56.2', '7.57.0', '7.59.0']
        - K8S_WEBLOG: [dd-lib-ruby-init-test-rails-gemsrb]
          K8S_WEBLOG_IMG: [ghcr.io/datadog/system-tests/dd-lib-ruby-init-test-rails-gemsrb:latest]
          K8S_SCENARIO: [K8S_LIB_INJECTION, K8S_LIB_INJECTION_UDS, K8S_LIB_INJECTION_NO_AC, K8S_LIB_INJECTION_NO_AC_UDS, K8S_LIB_INJECTION_PROFILING_DISABLED, K8S_LIB_INJECTION_PROFILING_ENABLED, K8S_LIB_INJECTION_PROFILING_OVERRIDE]
          K8S_LIB_INIT_IMG: ["gcr.io/datadoghq/dd-lib-ruby-init:latest", "ghcr.io/datadog/dd-trace-rb/dd-lib-ruby-init:latest_snapshot"]
          K8S_CLUSTER_VERSION: ['7.56.2', '7.57.0', '7.59.0']