name: Lint
description: "Run lints checks for project"
runs:
  using: composite
  steps:
    - name: Install runner
      uses: ./.github/actions/install_runner
    - run: source venv/bin/activate && black --check --diff .
      shell: bash
    - if: ${{ failure() }}
      shell: bash
      run:
        'echo "Lint fails, please have a look on https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md"

        exit 1

        '
    - run: source venv/bin/activate && pylint utils
      shell: bash
    - name: 'Install shellcheck'
      shell: bash
      run: sudo apt-get install -y shellcheck
    - name: 'Run shellcheck'
      shell: bash
      run: ./utils/scripts/shellcheck.sh
    - name: 'Run nodejs lint'
      shell: bash
      working-directory: ./utils/build/docker/nodejs/express4
      run: |
        if command -v npm &> /dev/null
        then
          npm install
          npm run lint
        else
          echo "WARN: npm command not found. Skipping nodejs lint."
        fi
        

