name: Lint
description: "Run lints checks for project"
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.9"
        cache: "pip"
    # TODO update to black 22+
    - run: pip install black==19.10b0 click==7.1.2 pylint==2.17.5
      shell: bash
    - run: black --check --diff .
      shell: bash
    - if: ${{ failure() }}
      shell: bash
      run:
        'echo "Lint fails, please have a look on https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md"

        exit 1

        '
    - run: pylint utils
      shell: bash
    - name: 'Install shellcheck'
      shell: bash
      run: sudo apt-get install -y shellcheck
    - name: 'Run shellcheck'
      shell: bash
      run: ./utils/scripts/shellcheck.sh
