name: Lint
description: "Run lints checks for project"
runs:
  using: composite
  steps:
    - name: Install runner
      uses: ./.github/actions/install_runner
    - run: source venv/bin/activate
      shell: bash
    - name: Black, pylint, tailing whitespaces, and yaml checks
      shell: bash
      run: ./format.sh --check
    - if: ${{ failure() }}
      shell: bash
      run:
        'echo "Lint fails, please have a look on https://github.com/DataDog/system-tests/blob/main/docs/edit/format.md"

        exit 1

        '
    - name: 'Install shellcheck'
      shell: bash
      run: sudo apt-get install -y shellcheck
    - name: 'Run shellcheck'
      shell: bash
      run: ./utils/scripts/shellcheck.sh
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: 'Run nodejs lint'
      shell: bash
      working-directory: ./utils/build/docker/nodejs/express
      run: |
        npm install
        npm run lint
