name: Get System Test Matrix
description: "Generates weblog matrix for each library"

inputs:
  java:
    description: "true to enable java matrix"
    required: false
  python:
    description: "true to enable python matrix"
    required: false
outputs:
  variant:
    description: "Matrix language/library and weblogs"
    value: ${{ steps.system-tests-matrix.outputs.variant }}
runs:
  using: composite
  steps:
    - name: Get matrix
      id: system-tests-matrix
      shell: bash
      #        echo "variant={\"variant\":[{\"library\":\"java\",\"weblog\":\"jersey-grizzly2\"},{\"library\":\"java\",\"weblog\":\"spring-boot\"}]}" >> $GITHUB_OUTPUT

      run: |
        if [ "${{ inputs.java}} " = true ] ; then
          jsonJava="$(cat ${{ github.action_path }}/java.json)"
        fi
        if [ "${{ inputs.python}} " = true ] ; then
          jsonJava="$(cat ${{ github.action_path }}/python.json)"
        fi
        jsonVersion="$(cat ${{ github.action_path }}/version.json)"

        #echo "$(ls)"
        #jsonJava="$(cat ${{ github.action_path }}/java.json)"
        #echo "variant=$(echo $jsonJava| jq -r tostring)" >> $GITHUB_OUTPUT

        #echo "$(echo $jsonJava|jq '.variant[]'),$(echo $jsonPython|jq '.variant[]')"
        #echo "$(echo $jsonJava|jq '.variant') $(echo $jsonPython|jq '.variant')"
   
        outputJson=$(echo "$(echo $jsonJava|jq '.variant') $(echo $jsonPython|jq '.variant')"| jq -s 'reduce .[] as $x ([]; . + $x)')
        outputJson={\"variant\":$outputJson,\"version\":$(echo $jsonVersion|jq '.version')}
        echo "variant=$(echo $outputJson| jq -r tostring)" >> $GITHUB_OUTPUT
