name: Get System Test Matrix
description: "Generates weblog matrix for each library"

inputs:
  java:
    description: "true to enable java matrix"
    required: false
  python:
    description: "true to enable python matrix"
    required: false
  ruby:
    description: "true to enable ruby matrix"
    required: false
  cpp:
    description: "true to enable cpp matrix"
    required: false
outputs:
  variant:
    description: "Matrix language/library and weblogs"
    value: ${{ steps.system-tests-matrix.outputs.variant }}
runs:
  using: composite
  steps:
    - name: Get matrix
      id: system-tests-matrix
      shell: bash
      run: |
        if [ "${{ inputs.java }}" = true ] ; then
          jsonJava="$(cat ${{ github.action_path }}/java.json)"
        fi
        if [ "${{ inputs.python }}" = true ] ; then
          jsonPython="$(cat ${{ github.action_path }}/python.json)"
        fi
        if [ "${{ inputs.ruby }}" = true ] ; then
          jsonRuby="$(cat ${{ github.action_path }}/ruby.json)"
        fi
        if [ "${{ inputs.cpp }}" = true ] ; then
          jsonCpp="$(cat ${{ github.action_path }}/cpp.json)"
        fi
        jsonVersion="$(cat ${{ github.action_path }}/version.json)"

        javaVariant=$(echo $jsonJava|jq '.variant')
        pythonVariant=$(echo $jsonPython|jq '.variant')
        rubyVariant=$(echo $jsonRuby|jq '.variant')
        cppVariant=$(echo $jsonCpp|jq '.variant')

        outputJson=$(echo "$javaVariant $pythonVariant $rubyVariant $cppVariant"| jq -s 'reduce .[] as $x ([]; . + $x)')
        outputJson={\"variant\":$outputJson,\"version\":$(echo $jsonVersion|jq '.version')}

        echo "variant=$(echo $outputJson| jq -r tostring)" >> $GITHUB_OUTPUT
