name: "Pull docker images"
description: "Pull docker images"
inputs:
  library:
    description: "Which library will be tested (python, cpp, java, ...)"
    required: true
  weblog:
    description: "Which weblog will be tested"
    required: true
  scenarios:
    description: "JSON array of scenarios that will be executed"
    required: true
  cleanup:
    description: "Whether to cleanup the disk to free up more space. Should be disabled when a larger machine can be used instead."
    required: false
    default: "true"
  dockerhub_username:
    description: "To prevent reaching docker hub API limits, provide a username and token to login to docker hub"
    required: false
    default: ""
  dockerhub_token:
    description: "To prevent reaching docker hub API limits, provide a username and token to login to docker hub"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Free some place for scenarios known to require lot of images
      if: ${{ (inputs.cleanup == 'true') && (contains(inputs.scenarios, '"INTEGRATIONS"') || contains(inputs.scenarios, '"CROSSED_TRACING_LIBRARIES"')) }}
      shell: bash
      run: |
        df -h

        echo "Removing docker images, dotnet, android, ghc, and CodeQL cache to free space"

        sudo rm -rf /usr/local/lib/android  # 9Gb!
        sudo rm -rf /opt/hostedtoolcache/CodeQL  # 5Gb !
        sudo rm -rf /usr/share/dotnet # 1Gb

        # sudo docker image prune --all --force  # if ever needed, but it's slow. Only 3Gb

        df -h

    - name: Get image list
      shell: bash
      run: |
        source venv/bin/activate
        python utils/scripts/get-image-list.py ${{ inputs.library }} ${{ inputs.weblog }} '${{ inputs.scenarios }}' > compose.yaml
      env:
        PYTHONPATH: "."

    - name: Login to Docker Hub
      if: inputs.dockerhub_username != '' && inputs.dockerhub_token != ''
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}

    - name: Pull
      shell: bash
      run: docker compose pull
