name: "Pull docker images"
description: "Pull docker images"
inputs:
  scenarios:
    description: "JSON array of scenarios that will be executed"
    default: "[]"
    required: true
  extra-images:
    description: "Comma-separated list of extra images to pull"
    default: ""
    required: false

runs:
  using: composite
  steps:
    - name: Free some place for scenarios known to require lot of images
      if: ${{ contains(inputs.scenarios, '"INTEGRATIONS"') || contains(inputs.scenarios, '"CROSSED_TRACING_LIBRARIES"') }}
      shell: bash
      run: |
        df -h

        echo "Removing docker images, dotnet, android, ghc, and CodeQL cache to free space"

        sudo rm -rf /usr/local/lib/android  # 9Gb!
        sudo rm -rf /opt/hostedtoolcache/CodeQL  # 5Gb !
        sudo rm -rf /usr/share/dotnet # 1Gb

        # sudo docker image prune --all --force  # if ever needed, but it's slow. Only 3Gb

        df -h

    - name: Get image list
      shell: bash
      run: |
        source venv/bin/activate
        python utils/scripts/get-image-list.py '${{ inputs.scenarios }}' > compose.yaml
      env:
        PYTHONPATH: "."
        EXTRA_IMAGES: "${{ matrix.extra-images }}"

    - name: Pull
      shell: bash
      run: docker compose pull
