name: "Pull docker images"
description: "Pull docker images"
inputs:
  scenarios:
    description: "JSON array of scenarios that will be executed"
    default: "[]"
    required: true

runs:
  using: composite
  steps:
    - name: Get image list
      shell: bash
      run: |
        source venv/bin/activate
        python utils/scripts/get-image-list.py '${{ inputs.scenarios }}' > compose.yaml
      env:
        PYTHONPATH: "."

    - name: Pull
      shell: bash
      run: docker compose pull -q
