name: "Pull docker images"
description: "Pull docker images"
inputs:
  library:
    description: "Which library will be tested (python, cpp, java, ...)"
    default: ""
  weblog:
    description: "Which weblog will be tested"
    default: ""
  scenarios:
    description: "JSON array, or comma separated list of scenarios that will be executed"
    required: true
  cleanup:
    description: "Whether to cleanup the disk to free up more space. Should be disabled when a larger machine can be used instead."
    required: false
    default: "true"
  dockerhub_username:
    description: "To prevent reaching docker hub API limits, provide a username and token to login to docker hub"
    required: false
    default: ""
  dockerhub_token:
    description: "To prevent reaching docker hub API limits, provide a username and token to login to docker hub"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Free some place for scenarios known to require lot of images
      if: ${{ (inputs.cleanup == 'true') || (contains(inputs.scenarios, '"INTEGRATIONS"') || contains(inputs.scenarios, '"CROSSED_TRACING_LIBRARIES"')) }}
      shell: bash
      run: |
        # Usage: clear_dir_with_rsync "/path/to/folder"
        clear_dir_with_rsync() {
          local dir="$1"

          # If no arg or path doesn't exist as a directory: do nothing
          [[ -z "$dir" || ! -d "$dir" ]] && return 0

          # Create an empty temp dir and sync it over the target with --delete
          local empty
          empty="$(mktemp -d)" || { echo "mktemp failed." >&2; return 1; }

          # -a for efficient traversal; --delete to remove extra files in target
          # --force to delete even if dirs are not empty; --omit-dir-times avoids dir mtime changes
          if sudo rsync -a --delete --force --omit-dir-times "$empty/" "$dir/"; then
            rmdir "$empty" 2>/dev/null || true
            return 0
          else
            # If it fails,
            # capture the exit code ($? → stored in st),
            # clean up the temporary empty dir,
            # and return the same exit code so the caller can see what went wrong.
            local st=$?
            rmdir "$empty" 2>/dev/null || true
            return $st
          fi
        }

        df -h
        du -h /usr/local/lib/android | grep -E '^[0-9]+G' | sort --numeric-sort

        echo "Removing docker images, dotnet, android, ghc, and CodeQL cache to free space"

        clear_dir_with_rsync /usr/local/lib/android  # 9Gb!
        clear_dir_with_rsync /opt/hostedtoolcache/CodeQL  # 5Gb !
        clear_dir_with_rsync /usr/share/dotnet # 1Gb

        # sudo docker image prune --all --force  # if ever needed, but it's slow. Only 3Gb

        df -h

    - name: Get image list
      shell: bash
      run: |
        source venv/bin/activate
        python utils/scripts/get-image-list.py '${{ inputs.scenarios }}' -l=${{ inputs.library }} -w=${{ inputs.weblog }} > compose.yaml
      env:
        PYTHONPATH: "."

    - name: Login to Docker Hub
      if: inputs.dockerhub_username != '' && inputs.dockerhub_token != ''
      uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}

#retry
    - name: Pull
      uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
      with:
        shell: bash
        command: docker compose pull
        timeout_minutes: 10
        retry_wait_seconds: 10
        max_attempts: 3
