name: Install_system_tests_runner
description: "Install python virtual env, and system dependencies, using github action cache if possible"

runs:
  using: composite
  steps:
    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # 5.6.0
      with:
        python-version: "3.12"
    - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809  # 4.2.4
      id: runner_cache
      with:
        path: venv
        key: runner_venv-${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
    - name: Build runner
      shell: bash
      if: steps.runner_cache.outputs.cache-hit != 'true'
      run: ./build.sh -i runner
    - name: Print versions
      shell: bash
      run: |
        source venv/bin/activate
        python --version
        pip freeze
