issuer: https://token.actions.githubusercontent.com

subject: repo:DataDog/system-tests:ref:refs/heads/main

claim_pattern:
  event_name: (workflow_dispatch|schedule)
  ref: refs/heads/main
  ref_protected: "true"
  job_workflow_ref: DataDog/system-tests/\.github/workflows/update-agent-protobuf\.yml@refs/heads/main

permissions:
  contents: write
  pull_requests: write

