# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apm_test_otel_client.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61pm_test_otel_client.proto\"!\n\x11StartOtelSpanArgs\x12\x0c\n\x04name\x18\x01 \x01(\t\"8\n\x13StartOtelSpanReturn\x12\x0f\n\x07span_id\x18\x01 \x01(\x0c\x12\x10\n\x08trace_id\x18\x02 \x01(\x0c\" \n\x12\x46inishOtelSpanArgs\x12\n\n\x02id\x18\x01 \x01(\x0c\"\x16\n\x14\x46inishOtelSpanReturn\"\x14\n\x12\x46lushOtelSpansArgs\"\x16\n\x14\x46lushOtelSpansReturn\"\x19\n\x17\x46lushOtelTraceStatsArgs\"\x1b\n\x19\x46lushOtelTraceStatsReturn\"\x14\n\x12StopOtelTracerArgs\"\x16\n\x14StopOtelTracerReturn2\xcf\x02\n\rAPMOtelClient\x12;\n\rStartOtelSpan\x12\x12.StartOtelSpanArgs\x1a\x14.StartOtelSpanReturn\"\x00\x12>\n\x0e\x46inishOtelSpan\x12\x13.FinishOtelSpanArgs\x1a\x15.FinishOtelSpanReturn\"\x00\x12:\n\nFlushSpans\x12\x13.FlushOtelSpansArgs\x1a\x15.FlushOtelSpansReturn\"\x00\x12I\n\x0f\x46lushTraceStats\x12\x18.FlushOtelTraceStatsArgs\x1a\x1a.FlushOtelTraceStatsReturn\"\x00\x12:\n\nStopTracer\x12\x13.StopOtelTracerArgs\x1a\x15.StopOtelTracerReturn\"\x00\x62\x06proto3')



_STARTOTELSPANARGS = DESCRIPTOR.message_types_by_name['StartOtelSpanArgs']
_STARTOTELSPANRETURN = DESCRIPTOR.message_types_by_name['StartOtelSpanReturn']
_FINISHOTELSPANARGS = DESCRIPTOR.message_types_by_name['FinishOtelSpanArgs']
_FINISHOTELSPANRETURN = DESCRIPTOR.message_types_by_name['FinishOtelSpanReturn']
_FLUSHOTELSPANSARGS = DESCRIPTOR.message_types_by_name['FlushOtelSpansArgs']
_FLUSHOTELSPANSRETURN = DESCRIPTOR.message_types_by_name['FlushOtelSpansReturn']
_FLUSHOTELTRACESTATSARGS = DESCRIPTOR.message_types_by_name['FlushOtelTraceStatsArgs']
_FLUSHOTELTRACESTATSRETURN = DESCRIPTOR.message_types_by_name['FlushOtelTraceStatsReturn']
_STOPOTELTRACERARGS = DESCRIPTOR.message_types_by_name['StopOtelTracerArgs']
_STOPOTELTRACERRETURN = DESCRIPTOR.message_types_by_name['StopOtelTracerReturn']
StartOtelSpanArgs = _reflection.GeneratedProtocolMessageType('StartOtelSpanArgs', (_message.Message,), {
  'DESCRIPTOR' : _STARTOTELSPANARGS,
  '__module__' : 'apm_test_otel_client_pb2'
  # @@protoc_insertion_point(class_scope:StartOtelSpanArgs)
  })
_sym_db.RegisterMessage(StartOtelSpanArgs)

StartOtelSpanReturn = _reflection.GeneratedProtocolMessageType('StartOtelSpanReturn', (_message.Message,), {
  'DESCRIPTOR' : _STARTOTELSPANRETURN,
  '__module__' : 'apm_test_otel_client_pb2'
  # @@protoc_insertion_point(class_scope:StartOtelSpanReturn)
  })
_sym_db.RegisterMessage(StartOtelSpanReturn)

FinishOtelSpanArgs = _reflection.GeneratedProtocolMessageType('FinishOtelSpanArgs', (_message.Message,), {
  'DESCRIPTOR' : _FINISHOTELSPANARGS,
  '__module__' : 'apm_test_otel_client_pb2'
  # @@protoc_insertion_point(class_scope:FinishOtelSpanArgs)
  })
_sym_db.RegisterMessage(FinishOtelSpanArgs)

FinishOtelSpanReturn = _reflection.GeneratedProtocolMessageType('FinishOtelSpanReturn', (_message.Message,), {
  'DESCRIPTOR' : _FINISHOTELSPANRETURN,
  '__module__' : 'apm_test_otel_client_pb2'
  # @@protoc_insertion_point(class_scope:FinishOtelSpanReturn)
  })
_sym_db.RegisterMessage(FinishOtelSpanReturn)

FlushOtelSpansArgs = _reflection.GeneratedProtocolMessageType('FlushOtelSpansArgs', (_message.Message,), {
  'DESCRIPTOR' : _FLUSHOTELSPANSARGS,
  '__module__' : 'apm_test_otel_client_pb2'
  # @@protoc_insertion_point(class_scope:FlushOtelSpansArgs)
  })
_sym_db.RegisterMessage(FlushOtelSpansArgs)

FlushOtelSpansReturn = _reflection.GeneratedProtocolMessageType('FlushOtelSpansReturn', (_message.Message,), {
  'DESCRIPTOR' : _FLUSHOTELSPANSRETURN,
  '__module__' : 'apm_test_otel_client_pb2'
  # @@protoc_insertion_point(class_scope:FlushOtelSpansReturn)
  })
_sym_db.RegisterMessage(FlushOtelSpansReturn)

FlushOtelTraceStatsArgs = _reflection.GeneratedProtocolMessageType('FlushOtelTraceStatsArgs', (_message.Message,), {
  'DESCRIPTOR' : _FLUSHOTELTRACESTATSARGS,
  '__module__' : 'apm_test_otel_client_pb2'
  # @@protoc_insertion_point(class_scope:FlushOtelTraceStatsArgs)
  })
_sym_db.RegisterMessage(FlushOtelTraceStatsArgs)

FlushOtelTraceStatsReturn = _reflection.GeneratedProtocolMessageType('FlushOtelTraceStatsReturn', (_message.Message,), {
  'DESCRIPTOR' : _FLUSHOTELTRACESTATSRETURN,
  '__module__' : 'apm_test_otel_client_pb2'
  # @@protoc_insertion_point(class_scope:FlushOtelTraceStatsReturn)
  })
_sym_db.RegisterMessage(FlushOtelTraceStatsReturn)

StopOtelTracerArgs = _reflection.GeneratedProtocolMessageType('StopOtelTracerArgs', (_message.Message,), {
  'DESCRIPTOR' : _STOPOTELTRACERARGS,
  '__module__' : 'apm_test_otel_client_pb2'
  # @@protoc_insertion_point(class_scope:StopOtelTracerArgs)
  })
_sym_db.RegisterMessage(StopOtelTracerArgs)

StopOtelTracerReturn = _reflection.GeneratedProtocolMessageType('StopOtelTracerReturn', (_message.Message,), {
  'DESCRIPTOR' : _STOPOTELTRACERRETURN,
  '__module__' : 'apm_test_otel_client_pb2'
  # @@protoc_insertion_point(class_scope:StopOtelTracerReturn)
  })
_sym_db.RegisterMessage(StopOtelTracerReturn)

_APMOTELCLIENT = DESCRIPTOR.services_by_name['APMOtelClient']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STARTOTELSPANARGS._serialized_start=30
  _STARTOTELSPANARGS._serialized_end=63
  _STARTOTELSPANRETURN._serialized_start=65
  _STARTOTELSPANRETURN._serialized_end=121
  _FINISHOTELSPANARGS._serialized_start=123
  _FINISHOTELSPANARGS._serialized_end=155
  _FINISHOTELSPANRETURN._serialized_start=157
  _FINISHOTELSPANRETURN._serialized_end=179
  _FLUSHOTELSPANSARGS._serialized_start=181
  _FLUSHOTELSPANSARGS._serialized_end=201
  _FLUSHOTELSPANSRETURN._serialized_start=203
  _FLUSHOTELSPANSRETURN._serialized_end=225
  _FLUSHOTELTRACESTATSARGS._serialized_start=227
  _FLUSHOTELTRACESTATSARGS._serialized_end=252
  _FLUSHOTELTRACESTATSRETURN._serialized_start=254
  _FLUSHOTELTRACESTATSRETURN._serialized_end=281
  _STOPOTELTRACERARGS._serialized_start=283
  _STOPOTELTRACERARGS._serialized_end=303
  _STOPOTELTRACERRETURN._serialized_start=305
  _STOPOTELTRACERRETURN._serialized_end=327
  _APMOTELCLIENT._serialized_start=330
  _APMOTELCLIENT._serialized_end=665
# @@protoc_insertion_point(module_scope)
