# ruff: noqa: SLF001

from pathlib import Path
import subprocess

import pytest

from utils import scenarios
from utils.scripts import update_mirror_images


def _write_lock(lock_path: Path) -> str:
    content = """\
# Auto-generated by: uv run bin/mirror_images.py lock
# Do not edit manually.
version: 1
images:
  datadog/agent:latest:
    digest: sha256:old-agent
    target: registry.ddbuild.io/system-tests/mirror/datadog/agent:latest
    tag: 7.80.1
  redis:7:
    digest: sha256:redis
    target: registry.ddbuild.io/system-tests/mirror/redis:7
    tag: '7'
"""
    lock_path.write_text(content, encoding="utf-8")
    return content


@scenarios.test_the_test
class Test_UpdateMirrorImages:
    def test_refresh_lock_file_removes_existing_lock(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
        lock_path = tmp_path / "mirror_images.lock.yaml"
        original_lock = _write_lock(lock_path)
        monkeypatch.setattr(update_mirror_images, "LOCK_YAML", lock_path)

        restored_lock = update_mirror_images._refresh_lock_file()

        assert restored_lock == original_lock
        assert not lock_path.exists()

    def test_refresh_lock_file_ignores_missing_lock(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
        lock_path = tmp_path / "mirror_images.lock.yaml"
        monkeypatch.setattr(update_mirror_images, "LOCK_YAML", lock_path)

        restored_lock = update_mirror_images._refresh_lock_file()

        assert restored_lock is None

    def test_main_refreshes_lock_before_lock_command(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
        lock_path = tmp_path / "mirror_images.lock.yaml"
        mirror_yaml = tmp_path / "mirror_images.yaml"
        buildkitd_toml = tmp_path / "buildkitd.toml"
        _write_lock(lock_path)
        calls: list[tuple[str, ...]] = []

        monkeypatch.chdir(tmp_path)
        monkeypatch.setattr(update_mirror_images, "REPO_ROOT", tmp_path)
        monkeypatch.setattr(update_mirror_images, "LOCK_YAML", lock_path)
        monkeypatch.setattr(update_mirror_images, "MIRROR_YAML", mirror_yaml)
        monkeypatch.setattr(update_mirror_images, "BUILDKITD_TOML", buildkitd_toml)

        def fake_collect_images(excluded: set[str]) -> list[str]:
            assert excluded == {"SKIP_ME"}
            return ["datadog/agent:latest"]

        monkeypatch.setattr(update_mirror_images, "collect_images", fake_collect_images)

        def fake_run_mirror_images(*args: str) -> None:
            calls.append(args)
            if args == ("lock",):
                assert not lock_path.exists()
                lock_path.write_text("new lock\n", encoding="utf-8")

        monkeypatch.setattr(update_mirror_images, "_run_mirror_images", fake_run_mirror_images)

        update_mirror_images.main({"SKIP_ME"}, skip_lock=False, refresh=True)

        assert calls == [
            ("add", "datadog/agent:latest"),
            ("lock",),
            ("buildkitd", "--output", str(buildkitd_toml)),
        ]
        assert lock_path.read_text(encoding="utf-8") == "new lock\n"

    def test_main_restores_lock_when_refresh_lock_command_fails(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
        lock_path = tmp_path / "mirror_images.lock.yaml"
        mirror_yaml = tmp_path / "mirror_images.yaml"
        buildkitd_toml = tmp_path / "buildkitd.toml"
        original_lock = _write_lock(lock_path)

        monkeypatch.chdir(tmp_path)
        monkeypatch.setattr(update_mirror_images, "REPO_ROOT", tmp_path)
        monkeypatch.setattr(update_mirror_images, "LOCK_YAML", lock_path)
        monkeypatch.setattr(update_mirror_images, "MIRROR_YAML", mirror_yaml)
        monkeypatch.setattr(update_mirror_images, "BUILDKITD_TOML", buildkitd_toml)
        monkeypatch.setattr(update_mirror_images, "collect_images", lambda _excluded: ["datadog/agent:latest"])

        def fake_run_mirror_images(*args: str) -> None:
            if args == ("lock",):
                lock_path.write_text("partial lock\n", encoding="utf-8")
                raise subprocess.CalledProcessError(1, ["mirror_images.py", "lock"])

        monkeypatch.setattr(update_mirror_images, "_run_mirror_images", fake_run_mirror_images)

        with pytest.raises(subprocess.CalledProcessError):
            update_mirror_images.main(set(), skip_lock=False, refresh=True)

        assert lock_path.read_text(encoding="utf-8") == original_lock

    def test_main_preserves_mirror_yaml_header_after_add(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
        mirror_yaml = tmp_path / "mirror_images.yaml"
        header = "---\n# Generated manifest.\n\n"
        mirror_yaml.write_text(f'{header}- "alpine:3.22"\n', encoding="utf-8")

        monkeypatch.chdir(tmp_path)
        monkeypatch.setattr(update_mirror_images, "REPO_ROOT", tmp_path)
        monkeypatch.setattr(update_mirror_images, "MIRROR_YAML", mirror_yaml)
        monkeypatch.setattr(update_mirror_images, "collect_images", lambda _excluded: ["datadog/agent:latest"])

        def fake_run_mirror_images(*args: str) -> None:
            assert args == ("add", "datadog/agent:latest")
            mirror_yaml.write_text('- "alpine:3.22"\n- "datadog/agent:latest"\n', encoding="utf-8")

        monkeypatch.setattr(update_mirror_images, "_run_mirror_images", fake_run_mirror_images)

        update_mirror_images.main(set(), skip_lock=True)

        assert mirror_yaml.read_text(encoding="utf-8") == (f'{header}- "alpine:3.22"\n- "datadog/agent:latest"\n')

    def test_main_rejects_refresh_with_skip_lock(self):
        with pytest.raises(ValueError, match="refresh cannot be used when skip_lock is true"):
            update_mirror_images.main(set(), skip_lock=True, refresh=True)
