# ruff: noqa: SLF001

from pathlib import Path
import subprocess

import pytest
import yaml

from utils import scenarios
from utils.scripts import update_mirror_images


def _write_lock(lock_path: Path) -> str:
    content = """\
# Auto-generated by: uv run bin/mirror_images.py lock
# Do not edit manually.
version: 1
images:
  datadog/agent:latest:
    digest: sha256:old-agent
    target: registry.ddbuild.io/system-tests/mirror/datadog/agent:latest
    tag: 7.80.1
  redis:7:
    digest: sha256:redis
    target: registry.ddbuild.io/system-tests/mirror/redis:7
    tag: '7'
"""
    lock_path.write_text(content, encoding="utf-8")
    return content


@scenarios.test_the_test
class Test_UpdateMirrorImages:
    def test_refresh_lock_file_removes_existing_lock(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
        lock_path = tmp_path / "mirror_images.lock.yaml"
        original_lock = _write_lock(lock_path)
        monkeypatch.setattr(update_mirror_images, "LOCK_YAML", lock_path)

        restored_lock = update_mirror_images._refresh_lock_file()

        assert restored_lock == original_lock
        assert not lock_path.exists()

    def test_refresh_lock_file_ignores_missing_lock(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
        lock_path = tmp_path / "mirror_images.lock.yaml"
        monkeypatch.setattr(update_mirror_images, "LOCK_YAML", lock_path)

        restored_lock = update_mirror_images._refresh_lock_file()

        assert restored_lock is None

    def test_main_refreshes_lock_before_lock_command(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
        lock_path = tmp_path / "mirror_images.lock.yaml"
        mirror_yaml = tmp_path / "mirror_images.yaml"
        buildkitd_toml = tmp_path / "buildkitd.toml"
        _write_lock(lock_path)
        calls: list[tuple[str, ...]] = []

        monkeypatch.chdir(tmp_path)
        monkeypatch.setattr(update_mirror_images, "REPO_ROOT", tmp_path)
        monkeypatch.setattr(update_mirror_images, "LOCK_YAML", lock_path)
        monkeypatch.setattr(update_mirror_images, "MIRROR_YAML", mirror_yaml)
        monkeypatch.setattr(update_mirror_images, "BUILDKITD_TOML", buildkitd_toml)

        def fake_collect_images(excluded: set[str]) -> list[str]:
            assert excluded == {"SKIP_ME"}
            return ["datadog/agent:latest"]

        monkeypatch.setattr(update_mirror_images, "collect_images", fake_collect_images)

        def fake_run_mirror_images(*args: str) -> None:
            calls.append(args)
            if args == ("lock",):
                assert not lock_path.exists()
                lock_path.write_text("new lock\n", encoding="utf-8")

        monkeypatch.setattr(update_mirror_images, "_run_mirror_images", fake_run_mirror_images)

        update_mirror_images.main({"SKIP_ME"}, skip_lock=False, refresh=True)

        assert calls == [
            ("add", "datadog/agent:latest"),
            ("lock",),
            ("buildkitd", "--output", str(buildkitd_toml)),
        ]
        assert lock_path.read_text(encoding="utf-8") == "new lock\n"

    def test_main_restores_lock_when_refresh_lock_command_fails(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
        lock_path = tmp_path / "mirror_images.lock.yaml"
        mirror_yaml = tmp_path / "mirror_images.yaml"
        buildkitd_toml = tmp_path / "buildkitd.toml"
        original_lock = _write_lock(lock_path)

        monkeypatch.chdir(tmp_path)
        monkeypatch.setattr(update_mirror_images, "REPO_ROOT", tmp_path)
        monkeypatch.setattr(update_mirror_images, "LOCK_YAML", lock_path)
        monkeypatch.setattr(update_mirror_images, "MIRROR_YAML", mirror_yaml)
        monkeypatch.setattr(update_mirror_images, "BUILDKITD_TOML", buildkitd_toml)
        monkeypatch.setattr(update_mirror_images, "collect_images", lambda _excluded: ["datadog/agent:latest"])

        def fake_run_mirror_images(*args: str) -> None:
            if args == ("lock",):
                lock_path.write_text("partial lock\n", encoding="utf-8")
                raise subprocess.CalledProcessError(1, ["mirror_images.py", "lock"])

        monkeypatch.setattr(update_mirror_images, "_run_mirror_images", fake_run_mirror_images)

        with pytest.raises(subprocess.CalledProcessError):
            update_mirror_images.main(set(), skip_lock=False, refresh=True)

        assert lock_path.read_text(encoding="utf-8") == original_lock

    @staticmethod
    def _setup_mirror_yaml(
        tmp_path: Path, monkeypatch: pytest.MonkeyPatch, *, serializer_emits_marker: bool = False
    ) -> Path:
        """Point the script at a temp mirror_images.yaml and fake `add` rewriting it.

        The real dd-repo-tools `add` rewrites the file through a YAML parser, so it
        drops comments, and only touches the file when it actually adds an image.
        """
        mirror_yaml = tmp_path / "mirror_images.yaml"
        monkeypatch.chdir(tmp_path)
        monkeypatch.setattr(update_mirror_images, "REPO_ROOT", tmp_path)
        monkeypatch.setattr(update_mirror_images, "MIRROR_YAML", mirror_yaml)
        monkeypatch.setattr(update_mirror_images, "BUILDKITD_TOML", tmp_path / "buildkitd.toml")
        monkeypatch.setattr(update_mirror_images, "collect_images", lambda _excluded: ["redis:7"])

        def fake_run_mirror_images(*args: str) -> None:
            if args[0] != "add":
                return
            body = "".join(f'- "{image}"\n' for image in args[1:])
            if serializer_emits_marker:
                body = "---\n" + body
            mirror_yaml.write_text(body, encoding="utf-8")  # comments dropped, as the real tool does

        monkeypatch.setattr(update_mirror_images, "_run_mirror_images", fake_run_mirror_images)
        return mirror_yaml

    def test_main_normalizes_to_the_canonical_header(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
        mirror_yaml = self._setup_mirror_yaml(tmp_path, monkeypatch)
        mirror_yaml.write_text('# manually edited header\n- "alpine:3.22"\n', encoding="utf-8")

        update_mirror_images.main(set(), skip_lock=True)

        content = mirror_yaml.read_text(encoding="utf-8")
        expected_header = update_mirror_images.MIRROR_YAML_HEADER
        assert content.startswith(expected_header), f"canonical header was not applied:\n{content}"
        assert '- "redis:7"' in content

    def test_main_canonicalizes_an_unchanged_file(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
        mirror_yaml = self._setup_mirror_yaml(tmp_path, monkeypatch)
        monkeypatch.setattr(update_mirror_images, "_run_mirror_images", lambda *_args: None)  # adds nothing
        original = '# manually edited header\n- "redis:7"\n'
        mirror_yaml.write_text(original, encoding="utf-8")

        update_mirror_images.main(set(), skip_lock=True)

        content = mirror_yaml.read_text(encoding="utf-8")
        assert content == update_mirror_images.MIRROR_YAML_HEADER + '- "redis:7"\n'

    def test_main_writes_the_default_header_on_first_run(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
        mirror_yaml = self._setup_mirror_yaml(tmp_path, monkeypatch)
        assert not mirror_yaml.exists()

        update_mirror_images.main(set(), skip_lock=True)

        content = mirror_yaml.read_text(encoding="utf-8")
        assert content.startswith(update_mirror_images.MIRROR_YAML_HEADER)
        assert '- "redis:7"' in content

    def test_main_does_not_produce_two_yaml_documents(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
        """The canonical header plus a serializer marker must stay one document."""
        mirror_yaml = self._setup_mirror_yaml(tmp_path, monkeypatch, serializer_emits_marker=True)
        mirror_yaml.write_text('# manually edited header\n- "alpine:3.22"\n', encoding="utf-8")

        update_mirror_images.main(set(), skip_lock=True)

        content = mirror_yaml.read_text(encoding="utf-8")
        assert not any(line.strip() == "---" for line in content.splitlines()), content
        assert yaml.safe_load(content) == ["redis:7"]

    def test_main_rejects_refresh_with_skip_lock(self):
        with pytest.raises(ValueError, match="refresh cannot be used when skip_lock is true"):
            update_mirror_images.main(set(), skip_lock=True, refresh=True)
