name: Pull Request Title
on:
  pull_request:
  # pull_request_target:
    types: [edited]
    # branches:
    #   - 'main'
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get previous target branch
        uses: ./.github/actions/get_target_branch
        id: get-previous-target-branch
        with:
          text: ${{ github.event.changes.title }}

      - name: Get current target branch
        uses: ./.github/actions/get_target_branch
        id: get-current-target-branch
        with:
          text: ${{ github.event.pull_request.title }}

      # - name: debug
      #   run: echo "${{ steps.get-previous-target-branch.outputs.target-branch }} ${{ steps.get-current-target-branch.outputs.target-branch }}"

      - name: Check target branch change
        if: ${{ steps.get-previous-target-branch.outputs.target-branch }} != ${{ steps.get-current-target-branch.outputs.target-branch }}
        run: echo "IT CHANGED"

