name: Pull Request Title
on:
  pull_request:
  # pull_request_target:
    types: [opened, edited, synchronize]
    # branches:
    #   - 'main'
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_CONTEXT"
