name: Testing the test

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - "**"

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install -r requirements.txt
    - run: black --check --diff .
    - run: PYTHONPATH="$PWD" python utils/test_the_test.py
  test-the-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - library: cpp
            weblog-variant: nginx
          - library: dotnet
            weblog-variant: poc
          - library: golang
            weblog-variant: net-http
          - library: golang
            weblog-variant: gorilla
          - library: java
            weblog-variant: spring-boot-poc
          - library: nodejs
            weblog-variant: express-poc
          - library: php
            weblog-variant: apache-mod
          - library: python
            weblog-variant: flask-poc
          - library: python
            weblog-variant: uwsgi-poc
          - library: ruby
            weblog-variant: sinatra-poc
      fail-fast: false
    env:
      TEST_LIBRARY: ${{ matrix.library }}
      WEBLOG_VARIANT: ${{ matrix.weblog-variant }}
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load library binary
        if: ${{ matrix.library != 'cpp' && matrix.library != 'java' && matrix.library != 'php' && matrix.library != 'python' }}
        run: ./utils/scripts/load-binary.sh ${{ matrix.library }}

      # uncomment this block once DataDog/dd-appsec-php-internal is public
      # - name: Load library PHP appsec binary
      #   if: ${{ matrix.library == 'php' }}
      #   run: ./utils/scripts/load-binary.sh php_appsec

      - name: Load library binary
        if: ${{ matrix.library == 'python' }}
        run: echo "ddtrace @ git+https://github.com/DataDog/dd-trace-py.git" > binaries/python-load-from-pip

      - name: Build
        run: ./build.sh

      - name: Run default scenario
        run: ./run.sh

      - name: Run missing AppSec rules file
        run: ./run.sh APPSEC_MISSING_RULES

      - name: Compress logs
        if: ${{ always() }}
        run: tar -czvf artifact.tar.gz $(ls | grep logs)

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: logs_${{ matrix.library }}_${{ matrix.weblog-variant }}
          path: artifact.tar.gz
