name: Testing the test

on:
  workflow_dispatch: {}
  schedule:
    - cron:  '00 02 * * 2-6'
  pull_request:
    branches:
      - "**"
env:
  REGISTRY: ghcr.io

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: pip install -r requirements.txt
    - run: black --check --diff .
    - if: ${{ failure() }}
      run: |
        echo "Lint fails, please have a look on https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md"
        exit 1
    - run: mkdir -p logs/docker/weblog/logs/
    - run: PYTHONPATH="$PWD" pytest utils/test_the_test

  test-the-tests:
    runs-on: ubuntu-latest
    needs: lint_and_test
    strategy:
      matrix:
        include:
          - library: cpp
            weblog-variant: nginx
            version: prod

          - library: dotnet
            weblog-variant: poc
            version: dev
          - library: dotnet
            weblog-variant: poc
            version: prod

          - library: golang
            weblog-variant: net-http
            version: dev
          - library: golang
            weblog-variant: net-http
            version: prod
          - library: golang
            weblog-variant: gorilla
            version: dev
          - library: golang
            weblog-variant: gorilla
            version: prod
          - library: golang
            weblog-variant: echo
            version: dev
          - library: golang
            weblog-variant: echo
            version: prod
          - library: golang
            weblog-variant: chi
            version: dev
          - library: golang
            weblog-variant: chi
            version: prod
          - library: golang
            weblog-variant: gin
            version: dev
          - library: golang
            weblog-variant: gin
            version: prod

          - library: java
            weblog-variant: spring-boot
            version: prod
          - library: java
            weblog-variant: spring-boot-jetty
            version: prod
          - library: java
            weblog-variant: jersey-grizzly2
            version: prod
          - library: java
            weblog-variant: resteasy-netty3
            version: prod
          - library: java
            weblog-variant: ratpack
            version: prod
          - library: java
            weblog-variant: vertx3
            version: prod

          - library: nodejs
            weblog-variant: express4
            version: dev
          - library: nodejs
            weblog-variant: express4
            version: prod
          - library: nodejs
            weblog-variant: express4-typescript
            version: dev
          - library: nodejs
            weblog-variant: express4-typescript
            version: prod

          - library: php
            weblog-variant: apache-mod-8.1
            version: prod
          - library: php
            weblog-variant: apache-mod-8.1
            version: dev
          - library: php
            weblog-variant: apache-mod-8.0
            version: prod
          - library: php
            weblog-variant: apache-mod-8.0
            version: dev
          - library: php
            weblog-variant: apache-mod-7.4
            version: prod
          - library: php
            weblog-variant: apache-mod-7.4
            version: dev
          - library: php
            weblog-variant: apache-mod-7.3
            version: prod
          - library: php
            weblog-variant: apache-mod-7.3
            version: dev
          # - library: php
          #   weblog-variant: apache-mod-7.2
          #   version: prod
          - library: php
            weblog-variant: apache-mod-7.2
            version: dev
          # - library: php
          #   weblog-variant: apache-mod-7.1
          #   version: prod
          - library: php
            weblog-variant: apache-mod-7.1
            version: dev
          # - library: php
          #   weblog-variant: apache-mod-7.0
          #   version: prod
          - library: php
            weblog-variant: apache-mod-7.0
            version: dev
          - library: php
            weblog-variant: apache-mod-8.1-zts
            version: prod
          - library: php
            weblog-variant: apache-mod-8.1-zts
            version: dev
          - library: php
            weblog-variant: apache-mod-8.0-zts
            version: prod
          - library: php
            weblog-variant: apache-mod-8.0-zts
            version: dev
          - library: php
            weblog-variant: apache-mod-7.4-zts
            version: prod
          - library: php
            weblog-variant: apache-mod-7.4-zts
            version: dev
          - library: php
            weblog-variant: apache-mod-7.3-zts
            version: prod
          - library: php
            weblog-variant: apache-mod-7.3-zts
            version: dev
          # - library: php
          #   weblog-variant: apache-mod-7.2-zts
          #   version: prod
          - library: php
            weblog-variant: apache-mod-7.2-zts
            version: dev
          # - library: php
          #   weblog-variant: apache-mod-7.1-zts
          #   version: prod
          - library: php
            weblog-variant: apache-mod-7.1-zts
            version: dev
          # - library: php
          #   weblog-variant: apache-mod-7.0-zts
          #   version: prod
          - library: php
            weblog-variant: apache-mod-7.0-zts
            version: dev
          - library: php
            weblog-variant: php-fpm-8.1
            version: prod
          - library: php
            weblog-variant: php-fpm-8.1
            version: dev
          - library: php
            weblog-variant: php-fpm-8.0
            version: prod
          - library: php
            weblog-variant: php-fpm-8.0
            version: dev
          - library: php
            weblog-variant: php-fpm-7.4
            version: prod
          - library: php
            weblog-variant: php-fpm-7.4
            version: dev
          - library: php
            weblog-variant: php-fpm-7.3
            version: prod
          - library: php
            weblog-variant: php-fpm-7.3
            version: dev
          # - library: php
          #   weblog-variant: php-fpm-7.2
          #   version: prod
          - library: php
            weblog-variant: php-fpm-7.2
            version: dev
          # - library: php
          #   weblog-variant: php-fpm-7.1
          #   version: prod
          - library: php
            weblog-variant: php-fpm-7.1
            version: dev
          # - library: php
          #   weblog-variant: php-fpm-7.0
          #   version: prod
          - library: php
            weblog-variant: php-fpm-7.0
            version: dev
          - library: python
            weblog-variant: flask-poc
            version: dev
          - library: python
            weblog-variant: flask-poc
            version: prod
          - library: python
            weblog-variant: uwsgi-poc
            version: dev
          - library: python
            weblog-variant: uwsgi-poc
            version: prod
          - library: python
            weblog-variant: django-poc
            version: dev
          - library: python
            weblog-variant: django-poc
            version: prod
          # - library: python
          #   weblog-variant: pylons
          #   version: dev
          # - library: python
          #   weblog-variant: pylons
          #   version: prod

          - library: ruby
            weblog-variant: rack
            version: dev
          - library: ruby
            weblog-variant: rack
            version: prod

          - library: ruby
            weblog-variant: sinatra14
            version: dev
          - library: ruby
            weblog-variant: sinatra14
            version: prod
          - library: ruby
            weblog-variant: sinatra20
            version: dev
          - library: ruby
            weblog-variant: sinatra20
            version: prod
          - library: ruby
            weblog-variant: sinatra21
            version: dev
          - library: ruby
            weblog-variant: sinatra21
            version: prod

          - library: ruby
            weblog-variant: rails32
            version: dev
          - library: ruby
            weblog-variant: rails32
            version: prod
          - library: ruby
            weblog-variant: rails40
            version: dev
          - library: ruby
            weblog-variant: rails40
            version: prod
          - library: ruby
            weblog-variant: rails41
            version: dev
          - library: ruby
            weblog-variant: rails41
            version: prod
          - library: ruby
            weblog-variant: rails42
            version: dev
          - library: ruby
            weblog-variant: rails42
            version: prod
          - library: ruby
            weblog-variant: rails50
            version: dev
          - library: ruby
            weblog-variant: rails50
            version: prod
          - library: ruby
            weblog-variant: rails51
            version: dev
          - library: ruby
            weblog-variant: rails51
            version: prod
          - library: ruby
            weblog-variant: rails52
            version: dev
          - library: ruby
            weblog-variant: rails52
            version: prod
          - library: ruby
            weblog-variant: rails60
            version: dev
          - library: ruby
            weblog-variant: rails60
            version: prod
          - library: ruby
            weblog-variant: rails61
            version: dev
          - library: ruby
            weblog-variant: rails61
            version: prod
          - library: ruby
            weblog-variant: rails70
            version: dev
          - library: ruby
            weblog-variant: rails70
            version: prod
      fail-fast: false
    env:
      TEST_LIBRARY: ${{ matrix.library }}
      WEBLOG_VARIANT: ${{ matrix.weblog-variant }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load WAF rules
        if: ${{ matrix.version == 'dev' }}
        run: ./utils/scripts/load-binary.sh waf_rule_set
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Load library binary
        if: ${{ matrix.version == 'dev' && matrix.library != 'php' }}
        run: ./utils/scripts/load-binary.sh ${{ matrix.library }}

      - name: Load library PHP appsec binary
        if: ${{ matrix.version == 'dev' && matrix.library == 'php' }}
        run: ./utils/scripts/load-binary.sh php_appsec
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Load agent binary
        if: ${{ matrix.version == 'dev' }}
        run: ./utils/scripts/load-binary.sh agent

      - name: Log in to the Container registry
        if: ${{ matrix.library == 'ruby' }}
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Build
        run: ./build.sh

      - name: Run default scenario
        run: ./run.sh
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}

      # - name: Run REMOTE_CONFIG_MOCKED_BACKEND scenario
      #   run: ./run.sh REMOTE_CONFIG_MOCKED_BACKEND
      #   env:
      #     DD_API_KEY: ${{ secrets.DD_API_KEY }}

      - name: Run APPSEC_CUSTOM_RULES scenario
        run: ./run.sh APPSEC_CUSTOM_RULES
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}

      - name: Run APPSEC_RULES_MONITORING_WITH_ERRORS scenario
        run: ./run.sh APPSEC_RULES_MONITORING_WITH_ERRORS
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}

      - name: Run PROFILING test
        if: ${{ matrix.library == 'nodejs' }}
        run: ./run.sh PROFILING
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}

      - name: Run UDS scenario
        if: ${{ matrix.library != 'php' && matrix.library != 'cpp' }}
        run: ./run.sh UDS
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}

      - name: Run CGROUP scenario
        run: ./run.sh CGROUP
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}

      - name: Run APPSEC_DISABLED scenario
        run: ./run.sh APPSEC_DISABLED
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}

      - name: Run APPSEC_LOW_WAF_TIMEOUT scenario
        run: ./run.sh APPSEC_LOW_WAF_TIMEOUT
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}

      - name: Run APPSEC_CUSTOM_OBFUSCATION scenario
        run: ./run.sh APPSEC_CUSTOM_OBFUSCATION
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}

      - name: Run APPSEC_RATE_LIMITER scenario
        run: ./run.sh APPSEC_RATE_LIMITER
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}

      - name: Run missing AppSec rules file
        run: ./run.sh APPSEC_MISSING_RULES
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}

      - name: Run LIBRARY_CONF_CUSTOM_HEADERS_SHORT scenario
        run: ./run.sh LIBRARY_CONF_CUSTOM_HEADERS_SHORT
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}

      - name: Run LIBRARY_CONF_CUSTOM_HEADERS_LONG scenario
        run: ./run.sh LIBRARY_CONF_CUSTOM_HEADERS_LONG
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}

      - name: Compress logs
        if: ${{ always() }}
        run: tar -czvf artifact.tar.gz $(ls | grep logs)

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: logs_${{ matrix.library }}_${{ matrix.weblog-variant }}_${{ matrix.version }}
          path: artifact.tar.gz

      - name: Print fancy log report
        if: ${{ always() }}
        run: python utils/scripts/markdown_logs.py >> $GITHUB_STEP_SUMMARY

  peformances:
    runs-on: ubuntu-latest
    needs: lint_and_test
    env:
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run
        run: ./scenarios/perfs/run.sh golang
      - name: Display
        run: python scenarios/perfs/process.py
