name: "Compute scenarios to run"

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      run_all:
        description: "Shall we run all scenarios"
        value: ${{ jobs.main.outputs.run_all }}
      run_open_telemetry:
        description: "Shall we run open-telemetry scenarios"
        value: ${{ jobs.main.outputs.run_open_telemetry }}
      run_sampling:
        description: "Shall we run sampling scenarios"
        value: ${{ jobs.main.outputs.run_sampling }}

jobs:
  main:
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      run_all: ${{ steps.compute_run_all.outputs.result }}
      run_open_telemetry: ${{ steps.compute_open_telemetry.outputs.result }}
      run_sampling: ${{ steps.compute_sampling.outputs.result }}
    steps:
      - name: Compute run_all
        id: compute_run_all
        run: |
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            echo "result=true" >> $GITHUB_OUTPUT

          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "result=true" >> $GITHUB_OUTPUT

          elif [ "${{ contains(github.event.pull_request.labels.*.name, 'run-all-scenarios') }}" == "true" ]; then
            echo "result=true" >> $GITHUB_OUTPUT

          else
            echo "result=false" >> $GITHUB_OUTPUT
          fi

          echo "Result: $GITHUB_OUTPUT"

      - name: Compute run_open_telemetry
        id: compute_open_telemetry
        run: |
          if [ "${{ contains(github.event.pull_request.labels.*.name, 'run-open-telemetry-scenarios') }}" == "true" ]; then
            echo "result=true" >> $GITHUB_OUTPUT

          else
            echo "result=false" >> $GITHUB_OUTPUT
          fi

          echo "Result: $GITHUB_OUTPUT"

      - name: Compute run_sampling
        id: compute_sampling
        run: |
          if [ "${{ steps.compute_run_all.outputs.result }}" == "true" ]; then
            echo "result=true" >> $GITHUB_OUTPUT

          elif [ "${{ contains(github.event.pull_request.labels.*.name, 'run-sampling-scenario') }}" == "true" ]; then
            echo "result=true" >> $GITHUB_OUTPUT

          else
            echo "result=false" >> $GITHUB_OUTPUT
          fi

          echo "Result: $GITHUB_OUTPUT"

      - name: Print results
        run: |
          echo "Run all: -> ${{ steps.compute_run_all.outputs.result }}"
          echo "Run open telemetry: -> ${{ steps.compute_open_telemetry.outputs.result }}"
          echo "Run sampling: -> ${{ steps.compute_sampling.outputs.result }}"
