name: "Compute scenarios to run"

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      scenarios:
        description: "JSON array of scenarios to run"
        value: ${{ jobs.main.outputs.scenarios }}
      scenarios_groups:
        description: "JSON array of scenarios groups to run"
        value: ${{ jobs.main.outputs.scenarios_groups }}

jobs:
  main:
    runs-on: ubuntu-latest
    outputs:
      scenarios: ${{ steps.compute_impacted_scenarios.outputs.scenarios }}
      scenarios_groups: ${{ steps.compute_impacted_scenarios.outputs.scenarios_groups }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'DataDog/system-tests'
      - name: Install runner
        uses: ./.github/actions/install_runner
      - name: Get original manifest
        run: |
          mkdir original/
          git --work-tree=original/ checkout HEAD -- manifests/
      - name: Get scenario map 
        run: ./run.sh MOCK_THE_TEST --collect-only --scenario-report
      - name: Compute impacted scenario
        id: compute_impacted_scenarios
        run: |
          source venv/bin/activate
          python utils/scripts/compute_impacted_scenario.py >> $GITHUB_OUTPUT
        env:
          PYTHONPATH: "."
          GITHUB_CONTEXT: ${{ toJSON(github) }}
