name: python-temporary-test

on:
  workflow_dispatch: {}
  schedule:
  - cron: 00 02 * * 2-6

env:
  REGISTRY: ghcr.io

jobs:
  end-to-end:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: 'DataDog/system-tests'
        branch: 'christophe-papazian/add_stderr_observability_for_nightly_on_standalone'
    - name: Install runner
      uses: ./.github/actions/install_runner
    - name: Pull images
      uses: ./.github/actions/pull_images
      with:
        library: python
        weblog: uwsgi-poc
        scenarios: '"APPSEC_STANDALONE"'
        dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build agent
      run: SYSTEM_TEST_BUILD_ATTEMPTS=3 ./build.sh -i agent
    - name: Build weblog
      id: build
      run: SYSTEM_TEST_BUILD_ATTEMPTS=3 ./build.sh python -i weblog -w uwsgi-poc
    - name: Run APPSEC_STANDALONE scenario
      if: always() && steps.build.outcome == 'success'
      run: ./run.sh APPSEC_STANDALONE
    
    - name: Compress logs
      id: compress_logs
      if: always() && steps.build.outcome == 'success'
      run: tar -czvf artifact.tar.gz $(ls | grep logs)
    - name: Upload artifact
      if: always() && steps.compress_logs.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        # log name convention to respect : logs_$SCENARIO-FAMILY_$LIBRARY_$WEBLOG_$CI-ENVIRONMENT
        name: logs_endtoend
        path: artifact.tar.gz
