name: Parametric
on:
  workflow_call:

env:
  REGISTRY: ghcr.io
jobs:
  parametric:
    runs-on:
      group: "APM Larger Runners"
    strategy:
      matrix:
        library:
          - cpp
          - dotnet
          - golang
          - java
          - nodejs
          - php
          - python
          - ruby
        version:
          - prod
          - dev
 
      fail-fast: false
    env:
      TEST_LIBRARY: ${{ matrix.library }}
      SYSTEM_TESTS_REPORT_ENVIRONMENT: ${{ matrix.version }}
      SYSTEM_TESTS_REPORT_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install runner
        uses: ./.github/actions/install_runner
      - name: Load library binary
        if: ${{ matrix.version == 'dev' }}
        run: ./utils/scripts/load-binary.sh ${{ matrix.library }}
      - name: Run parametric tests (with timeout)
        if: ${{ matrix.library == 'java' }}
        run: |
          set +e
          RUN_ATTEMPTS=1
          while [ $RUN_ATTEMPTS -le 3 ]; do
            echo "Running parametric test attempt $RUN_ATTEMPTS"
            timeout 720s ./run.sh PARAMETRIC
            status=$?
            #timneout returns 124 if it times out
            #if the return code is not 124, then we exit with the status
            if [ $status -ne 124 ]; then
              exit $status
              break
            fi
            RUN_ATTEMPTS=$((RUN_ATTEMPTS+1))
            if [ $RUN_ATTEMPTS -eq 4 ]; then
              #Max attempts reached, exit with 124
              exit 124
            fi
          done          
      - name: Run parametric (without timeout)
        if: ${{ matrix.library != 'java' }}
        run: ./run.sh PARAMETRIC
      - name: Compress logs
        id: compress_logs
        if: always()
        run: tar -czvf artifact.tar.gz $(ls | grep logs)
      - name: Upload artifact
        if: always() && steps.compress_logs.outcome == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: logs_parametric_${{ matrix.library}}_${{ matrix.version }}
          path: artifact.tar.gz
      - name: Upload results CI Visibility
        if: ${{ always() }}
        run: ./utils/scripts/upload_results_CI_visibility.sh ${{ matrix.version }} system-tests ${{ github.run_id }}-${{ github.run_attempt }}
        env:
          DD_API_KEY: ${{ secrets.DD_CI_API_KEY }}
      - name: Print fancy log report
        if: ${{ always() }}
        run: python utils/scripts/markdown_logs.py >> $GITHUB_STEP_SUMMARY
