name: Lib-injection tests

on:
  workflow_call:
    inputs:
      build_lib_injection_app_images:
        description: "Shall we build python base images for tests on python tracer"
        default: false
        required: false
        type: boolean
      library:
        description: "Library to test"
        required: true
        type: string
env:
  REGISTRY: ghcr.io

jobs:

  compute-matrix:
    name: Get weblogs for Lib-Injection tests
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.compute-matrix.outputs.matrix }}
      matrix_not_supported_langs: ${{ steps.compute-matrix.outputs.matrix_not_supported_langs }}
    steps:
    - name: Compute matrix
      id: compute-matrix
      shell: python
      run: |
        import json
        import os

        weblogs_not_supported_langs={
          "cpp":[],
          "cpp":[],
          "python":[],
          "nodejs":[],
          "dotnet":[],
          "ruby":[],
          "php":[],
          "java": ["jdk7-app"],
        }

        weblogs={
          "cpp":[],
          "cpp":[],
          "python":[],
          "nodejs":[],
          "dotnet":[],
          "ruby":[],
          "php":[],
          "java": ["dd-lib-java-init-test-app"],
        }

        result = weblogs["${{ inputs.library }}"]
        result_not_supported_langs = weblogs_not_supported_langs["${{ inputs.library }}"]

        with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
            print(f'matrix={json.dumps(result)}', file=fh)
            print(f'matrix_not_supported_langs={json.dumps(result_not_supported_langs)}', file=fh)

        print(json.dumps(result, indent=2))
        print(json.dumps(result_not_supported_langs, indent=2))

  lib-injection-init-image-validator:
    if: inputs.library == 'dotnet' || inputs.library == 'java' || inputs.library == 'python' || inputs.library == 'ruby' || inputs.library == 'nodejs'
    runs-on:
      group: "APM Larger Runners"
    permissions:
      contents: read
      packages: read
    needs: 
      - compute-matrix
    strategy:
      matrix:
        weblog: ${{ fromJson(needs.compute-matrix.outputs.matrix) }}
        version:      
          - prod
          - dev
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'DataDog/system-tests'

      - uses: ./.github/actions/init-image-validator
        name: 'Build and run lib init image validator scenarios'
        with:
          library: "${{inputs.library}}"
          weblog: "${{matrix.weblog}}"
          version: "${{matrix.version }}"
          is_lang_supported_version: 'true'


  k8s-lib-injection-tests:
    if: 1==2 && inputs.library == 'dotnet' || inputs.library == 'java' || inputs.library == 'python' || inputs.library == 'ruby' || inputs.library == 'nodejs'
    runs-on:
      group: "APM Larger Runners"
    permissions:
      contents: read
      packages: write
    needs: 
      - compute-matrix
    strategy:
      matrix:
        weblog: ${{ fromJson(needs.compute-matrix.outputs.matrix) }}
        version:      
          - latest
          - latest_snapshot
      fail-fast: false
    env:
      TEST_LIBRARY: ${{ inputs.library }}
      WEBLOG_VARIANT: ${{ matrix.weblog }}
      DOCKER_REGISTRY_IMAGES_PATH: ghcr.io/datadog
      DOCKER_IMAGE_TAG: ${{ matrix.version }}
      BUILDX_PLATFORMS: linux/amd64
      SYSTEM_TESTS_REPORT_ENVIRONMENT: dev
      SYSTEM_TESTS_REPORT_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'DataDog/system-tests'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
    
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.12.1 # 0.13.0 is causing the builds to fail
          install: true
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 1
        
      - name: Log in to the Container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # 3.0.0
        with:
          registry: ghcr.io/datadog
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build weblog base images (PR)
        if: inputs.build_lib_injection_app_images
        env:
          DOCKER_IMAGE_WEBLOG_TAG: ${{ github.sha }}
          APP_DOCKER_IMAGE_REPO: ghcr.io/datadog/system-tests/${{ matrix.weblog }}
        run: docker buildx build --platform linux/amd64 -t $APP_DOCKER_IMAGE_REPO:${{ github.sha }} -f utils/build/ssi/$TEST_LIBRARY/$WEBLOG_VARIANT/Dockerfile --push .
          
      - name: Build weblog latest base images
        #If we execute on system-tests-dashboard, we can't push the images because we don't have the permissions.
        #To asign the permissions, we need to configure the image on ghcr, but due to a issue we can't do it
        #The case is opened with github support
        if: github.ref == 'refs/heads/main' && github.event_name != 'schedule' && github.event_name != 'workflow_dispatch'
        env:
          DOCKER_IMAGE_WEBLOG_TAG: latest
          APP_DOCKER_IMAGE_REPO: ghcr.io/datadog/system-tests/${{ matrix.weblog }}
        run: |
          cd lib-injection/build/docker/$TEST_LIBRARY/$WEBLOG_VARIANT 
          LIBRARY_INJECTION_TEST_APP_IMAGE=$APP_DOCKER_IMAGE_REPO:latest ./build.sh
          cd ..

      - name: Install runner
        uses: ./.github/actions/install_runner       

      - name: Kubernetes lib-injection tests (using custom weblog image tag)
        if: inputs.build_lib_injection_app_images
        id: k8s-lib-injection-tests-custom-weblog-tag
        run: DOCKER_IMAGE_WEBLOG_TAG=${{ github.sha }} ./run.sh K8S_LIB_INJECTION_BASIC

      - name: Kubernetes lib-injection tests
        if: inputs.build_lib_injection_app_images != true
        id: k8s-lib-injection-tests
        run: ./run.sh K8S_LIB_INJECTION_FULL

      - name: Compress logs
        id: compress_logs
        if: always()
        run: tar -czvf artifact.tar.gz $(ls | grep logs)

      - name: Upload artifact
        if: always() && steps.compress_logs.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: logs_k8s-lib-injection_${{ inputs.library}}_${{matrix.weblog}}_${{ matrix.version == 'latest' && 'prod' || 'dev' }}
          path: artifact.tar.gz