name: Update agent protobuf deserializer

on:
  workflow_dispatch: {}
  schedule:
    - cron: "00 02 * * 2-6"

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          persist-credentials: false
      - name: Generate descriptor
        run: docker run --rm -v "$(pwd):/work" -w /work golang:1.24.5 /work/utils/scripts/update_protobuf.sh
      - uses: DataDog/dd-octo-sts-action@96a25462dbcb10ebf0bfd6e2ccc917d2ab235b9a # v1.0.4
        id: octo-sts
        with:
          scope: DataDog/system-tests
          policy: self.update-agent-protobuf.create-pr
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          commit-message: Update protobuf descriptors
          branch: actions/update-protobuf-descriptors
          title: Update protobuf descriptors
          body: Please check locally that everything is ok before merging
          token: ${{ steps.octo-sts.outputs.token }}
