name: Update telemetry keys

on:
  workflow_dispatch: {}
  repository_dispatch:
    types:
      - dd-go-commit
  pull_request:
    branches:
    - '**'


jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - run: ./tests/telemetry_intake/update.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update telemetry keys
          branch: actions/update-telemetry-keys
          title: Update telemetry keys
          body: Please check locally that everything is ok before merging
